Repository filecoin-project/lotus, pull requests merged in 2019-12, with the labels that each got.

#673 actors: Implement cron actor
  chain/actors/actor_cron.go
  chain/actors/actor_init.go
  chain/actors/actor_storagepower.go
  chain/actors/actors.go
  chain/actors/cbor_gen.go
  chain/blocksync/cbor_gen.go
  chain/gen/utils.go
  chain/stmgr/stmgr.go
  chain/types/cbor_gen.go
  chain/vm/invoker.go
  gen/main.go
Labels: fork_required

#720 Feat/dt subscribe, file Xfer round trip
  chain/deals/provider.go
  datatransfer/cbor-gen/main.go
  datatransfer/impl/dagservice/dagservice.go
  datatransfer/impl/graphsync/cbor_gen.go
  datatransfer/impl/graphsync/graphsync_impl.go
  datatransfer/impl/graphsync/graphsync_impl_test.go
  datatransfer/impl/graphsync/graphsync_receiver.go
  datatransfer/impl/graphsync/graphsync_receiver_test.go
  datatransfer/impl/graphsync/graphsync_whitebox_test.go
  datatransfer/message/cbor_gen.go
  datatransfer/types.go
Labels: team-shared-components

#695 chainval | type serialization
  chain/validation/applier.go
  chain/validation/lotus_test.go
  chain/validation/message.go
  chain/validation/message_test.go
  chain/validation/state.go
  chain/vm/validation_test.go
  go.mod
  go.sum
Labels: testing

#710 there is no real correlation between challenge count and len(winners)
  lib/sectorbuilder/simple.go
Labels: fork_required

#759 feat(datatransfer): switch to graphsync implementation
  chain/deals/cbor_gen.go
  chain/deals/client.go
  chain/deals/client_utils.go
  chain/deals/provider_utils.go
  chain/deals/request_validation_test.go
  datatransfer/impl/graphsync/graphsync_impl.go
  datatransfer/impl/graphsync/graphsync_impl_test.go
  datatransfer/impl/graphsync/graphsync_receiver.go
  datatransfer/impl/graphsync/graphsync_receiver_test.go
  datatransfer/impl/graphsync/graphsync_whitebox_test.go
  node/builder.go
  node/modules/client.go
  node/modules/dtypes/storage.go
  node/modules/storageminer.go
Labels: team-shared-components

#221 Lazy RLE+
  chain/actors/actor_miner.go
  chain/types/bitfield.go
  lib/rlepluslazy/bits.go
  lib/rlepluslazy/bits_test.go
  lib/rlepluslazy/bitvec.go
  lib/rlepluslazy/bitvec_test.go
  lib/rlepluslazy/interface.go
  lib/rlepluslazy/rleplus.go
  lib/rlepluslazy/rleplus_golden_test.go
  lib/rlepluslazy/rleplus_reader.go
  lib/rlepluslazy/rleplus_test.go
  lib/rlepluslazy/rleplus_writer.go
  lib/rlepluslazy/runs.go
  lib/rlepluslazy/runs_test.go
Labels: in progress

#797 Restart fPoSt after fail
  storage/fpost_run.go
  storage/fpost_sched.go
Labels: testnet

#790 Rename pledge-sector
  api/api_storage.go
  api/struct.go
  cmd/lotus-storage-miner/main.go
  cmd/lotus-storage-miner/sectors.go
  documentation/en/mining.md
  lotuspond/front/src/StorageNode.js
  node/impl/storminer.go
  storage/garbage.go
  storage/sector_states.go
Labels: testnet

#796 implement lotus-seed aggregation commands
  cmd/lotus-seed/main.go
  go.mod
  go.sum
  lib/sectorbuilder/sectorbuilder.go
Labels: testnet

#792 Handle reverts in precommit more correctly
  api/api_storage.go
  build/params_debug.go
  build/params_devnet.go
  chain/blocksync/cbor_gen.go
  chain/types/cbor_gen.go
  cmd/lotus-storage-miner/sectors.go
  node/impl/storminer.go
  storage/cbor_gen.go
  storage/sector_states.go
  storage/sector_types.go
  storage/sectors.go
Labels: testnet

#804 Fix retrieval of large files
  api/cbor_gen.go
  chain/actors/cbor_gen.go
  chain/blocksync/cbor_gen.go
  chain/types/cbor_gen.go
  go.mod
  go.sum
  paych/cbor_gen.go
  retrieval/cbor_gen.go
  storage/cbor_gen.go
Labels: testnet

#783 Fix/bad epost mining
  chain/stmgr/stmgr.go
  chain/sync.go
  node/impl/full/state.go
Labels: fork_required, testnet

#816 Move api struct to a seprate pkg
  api/api_common.go
  api/apistruct/permissioned.go
  api/apistruct/struct.go
  api/client/client.go
  cli/auth.go
  cmd/lotus-storage-miner/run.go
  cmd/lotus/rpc.go
  lib/auth/handler.go
  node/impl/common.go
  node/impl/storminer.go
  node/modules/core.go
Labels: testnet

#808 fix `IsTicketWinner` in ePoSt
  chain/gen/gen.go
  chain/sync.go
  chain/types/blockheader.go
  lib/sectorbuilder/sectorbuilder.go
  lib/sectorbuilder/simple.go
Labels: fork_required, testnet

#775 Reintegrate sector faults
  api/api_storage.go
  chain/actors/actor_miner.go
  chain/actors/actor_miner_test.go
  chain/actors/actor_paych_test.go
  chain/actors/cbor_gen.go
  chain/actors/harness2_test.go
  chain/types/bitfield.go
  chain/types/vmcontext.go
  chain/vm/mkactor.go
  chain/vm/syscalls.go
  chain/vm/vm.go
  gen/main.go
  storage/cbor_gen.go
  storage/sector_states.go
  storage/sector_types.go
  storage/sectors.go
Labels: fork_required, testnet

#814 implement a minimum miner size
  build/params_debug.go
  build/params_devnet.go
  build/params_shared.go
  chain/actors/actor_miner.go
  chain/types/bigint.go
  lotuspond/spawn.go
  miner/miner.go
Labels: testnet

#770 [DNM] Feat/dt extraction use go-fil-components/datatransfer
  chain/deals/client_utils.go
  chain/deals/provider.go
  chain/deals/provider_utils.go
  datatransfer/Makefile
  datatransfer/cbor-gen/main.go
  datatransfer/docs/README.md
  datatransfer/docs/markets-proposal.md
  datatransfer/docs/pull-flow.mmd
  datatransfer/docs/pull-flow.png
  datatransfer/docs/pull-flow.svg
  datatransfer/docs/push-flow.mmd
  datatransfer/docs/push-flow.png
  datatransfer/docs/retrieval-market-flow.mmd
  datatransfer/docs/retrieval-market-flow.png
  datatransfer/docs/storage-market-flow.mmd
  datatransfer/docs/storage-market-flow.png
  datatransfer/impl/dagservice/dagservice.go
  datatransfer/impl/graphsync/cbor_gen.go
  datatransfer/impl/graphsync/fixtures/lorem.txt
  datatransfer/impl/graphsync/graphsync_impl.go
  datatransfer/impl/graphsync/graphsync_impl_test.go
  datatransfer/impl/graphsync/graphsync_receiver.go
  datatransfer/impl/graphsync/graphsync_receiver_test.go
  datatransfer/impl/graphsync/graphsync_whitebox_test.go
  datatransfer/impl/graphsync/run_cbor_gen.go
  datatransfer/impl/graphsync/utils.go
  datatransfer/message/cbor_gen.go
  datatransfer/message/message.go
  datatransfer/message/message_test.go
  datatransfer/message/run_cbor_gen.go
  datatransfer/message/transfer_message.go
  datatransfer/message/transfer_request.go
  datatransfer/message/transfer_response.go
  datatransfer/network/interface.go
  datatransfer/network/libp2p_impl.go
  datatransfer/network/libp2p_impl_test.go
  datatransfer/testutil/testutil.go
  datatransfer/types.go
  go.mod
  go.sum
  node/modules/client.go
  node/modules/dtypes/storage.go
  node/modules/storageminer.go
Labels: team-shared-components

#715 chainval | multisig tests
  chain/validation/message.go
  chain/vm/validation_test.go
  go.mod
  go.sum
Labels: testing

#737 chainval | paych tests
  chain/validation/message.go
  chain/vm/validation_test.go
Labels: testing

#988 FORK: No power EPS Fix
  .circleci/config.yml
  build/forks.go
  chain/actors/actor_miner.go
  chain/actors/actor_storagepower.go
  chain/actors/forks.go
  chain/stmgr/fork_no_p_eps.go
  chain/stmgr/forks.go
  chain/stmgr/stmgr.go
Labels: fork_required
