Repository filecoin-project/lotus, pull requests merged in 2019-11, with the labels that each got.

#504 fix panic when close miner
  lib/jsonrpc/client.go
Labels: jsonrpc

#527 fix serialization of paych vouchers
  api/cbor_gen.go
  chain/actors/cbor_gen.go
  chain/deals/cbor_gen.go
  chain/deals/state_store.go
  chain/gen/gen.go
  chain/types/cbor_gen.go
  chain/types/voucher.go
  cli/client.go
  gen/main.go
  go.mod
  go.sum
  lib/sectorbuilder/mock.go
  lib/sectorbuilder/sectorbuilder.go
  lib/sectorbuilder/sectorbuilder_test.go
  node/hello/hello.go
  node/impl/client/client.go
  node/impl/paych/paych.go
  paych/cbor_gen.go
  paych/store.go
  retrieval/cbor_gen.go
  retrieval/client.go
  retrieval/miner.go
  retrieval/types.go
Labels: fork_required

#513 Refactor the PowerCmp function
  chain/types/blockheader.go
Labels: fork_required

#563 Don't try syncing to a chain if its not clearly heavier
  chain/blocksync/blocksync.go
  chain/blocksync/blocksync_client.go
  chain/blocksync/cbor_gen.go
  chain/store/store.go
  chain/sync.go
  chain/types/cbor_gen.go
  gen/main.go
  go.mod
  go.sum
  node/builder.go
  node/hello/hello.go
  node/modules/services.go
  storage/post.go
Labels: fork_required

#539 first pass at integrating chain-validation
  chain/validation/applier.go
  chain/validation/factories.go
  chain/validation/lotus_test.go
  chain/validation/message.go
  chain/validation/message_test.go
  chain/validation/state.go
  chain/vm/validation_test.go
  go.mod
  go.sum
Labels: team-shared-components, testing

#574 Implement response to data pull/push requests
  datatransfer/impl/graphsync/graphsync.go
  datatransfer/impl/graphsync/graphsync_test.go
Labels: team-shared-components

#567 Add TipSetKey as a concatenation of block CIDs, and use if for ChainGetTipSet, ChainGetRandomness.
  api/api_full.go
  api/struct.go
  chain/gen/gen.go
  chain/types/tipset.go
  chain/types/tipset_key.go
  chain/types/tipset_key_test.go
  cli/chain.go
  go.mod
  go.sum
  node/impl/full/chain.go
  node/modules/storageminer.go
  storage/miner.go
  storage/post.go
  storage/sector_states.go
Labels: in progress, team-shared-components

#607 responses alert subscribers when request is not accepted
  datatransfer/impl/graphsync/graphsync.go
  datatransfer/impl/graphsync/graphsync_test.go
  datatransfer/impl/graphsync/graphsync_whitebox_test.go
Labels: team-shared-components

#627 Feat/dt graphsync pullreqs
  datatransfer/impl/graphsync/graphsync.go
  datatransfer/impl/graphsync/graphsync_test.go
  datatransfer/types.go
  go.sum
Labels: team-shared-components

#645 Feat/dt initiator cleanup
  datatransfer/impl/graphsync/graphsync.go
  datatransfer/impl/graphsync/graphsync_test.go
  datatransfer/impl/graphsync/graphsync_whitebox_test.go
  datatransfer/types.go
  go.mod
  go.sum
Labels: team-shared-components

#651 Techdebt/dt split graphsync impl receiver
  datatransfer/impl/graphsync/graphsync_impl.go
  datatransfer/impl/graphsync/graphsync_impl_test.go
  datatransfer/impl/graphsync/graphsync_receiver.go
  datatransfer/impl/graphsync/graphsync_receiver_test.go
  datatransfer/impl/graphsync/utils.go
Labels: team-shared-components

#665 DTM sends data over graphsync for validated push requests
  datatransfer/impl/graphsync/graphsync_impl.go
  datatransfer/impl/graphsync/graphsync_impl_test.go
  datatransfer/impl/graphsync/graphsync_receiver.go
  datatransfer/message/message_test.go
  go.mod
  go.sum
Labels: team-shared-components
