Repository filecoin-project/lotus, pull requests merged in 2020-11, with the labels that each got.

#4764 Update to actors v2.3.0
  build/params_2k.go
  build/params_mainnet.go
  build/params_testground.go
  chain/actors/policy/policy.go
  chain/actors/policy/policy_test.go
  chain/stmgr/forks.go
  go.mod
  go.sum
Labels: impact/consensus

#4788 Add client deal-stats CLI
  cli/client.go
Labels: area/ux

#4783 Small consensus-critical fixes in 1.2.0
  chain/actors/params.go
  chain/vm/invoker.go
  chain/vm/invoker_test.go
  chain/vm/runtime.go
  chain/vm/vm.go
Labels: impact/consensus

#4862 Modify vesting schedule post-calico
  chain/stmgr/stmgr.go
Labels: impact/consensus

#3171 add sanity check for maximum block size
  chain/sub/incoming.go
Labels: impact/consensus

#4712 Check (pre)commit receipt before other checks in failed states
  extern/storage-sealing/fsm.go
  extern/storage-sealing/states_failed.go
Labels: area/sealing/fsm

#4830 Gas Balancing
  chain/vm/gas.go
  chain/vm/gas_v0.go
  chain/vm/runtime.go
  chain/vm/vm.go
  conformance/chaos/actor.go
  conformance/chaos/actor_test.go
  go.mod
  go.sum
  metrics/metrics.go
Labels: impact/consensus

#4903 Tweak handling of bad beneficaries in DeleteActor
  chain/vm/runtime.go
Labels: impact/consensus

#4914 CLI to get network version
  cli/state.go
Labels: area/ux
