Repository filecoin-project/lotus, pull requests merged in 2020-03, with the labels that each got.

#1308 Documentation updates
  documentation/en/.library.json
  documentation/en/cli.md
  documentation/en/join-testnet.md
Labels: documentation

#1326 Re: #1307: Provide ArgsUsage for all CLI commands
  cli/chain.go
  cli/client.go
  cli/log.go
  cli/multisig.go
  cli/net.go
  cli/paych.go
  cli/send.go
  cli/state.go
  cli/sync.go
  cli/wallet.go
Labels: documentation, ux

#1312 Re: #1239: Expose information about invoked messages
  api/api_full.go
  api/apistruct/struct.go
  build/version.go
  chain/stmgr/call.go
  chain/stmgr/utils.go
  chain/sync.go
  chain/vm/vm.go
  cli/client.go
  cli/state.go
  cmd/lotus-storage-miner/init.go
  miner/miner.go
  node/impl/full/state.go
  paych/paych.go
  storage/miner.go
  storage/sealing/checks.go
  storage/sealing/sealing.go
Labels: enhancement

#1347 fix initial reward actor balance
  build/params_shared.go
  chain/gen/genesis/t02_reward.go
  chain/vm/vm.go
  chain/vm/vm_test.go
Labels: fork_required

#1369 pass ticket count into reward application message
  chain/stmgr/stmgr.go
Labels: fork_required

#1388 Check for correct nonce before taking gas
  chain/vm/vm.go
Labels: fork_required

#1383 New Actor Addresses should be generated as per spec
  chain/validation/factories.go
  chain/vm/runtime.go
  chain/vm/vm.go
  go.mod
  go.sum
Labels: fork_required

#1313 Re: #1302: Refine invalid message filtering
  chain/messagepool/messagepool.go
  chain/sub/incoming.go
Labels: enhancement

#1436 Use blake2b, not SHA, for VRFs
  chain/gen/gen.go
  chain/sync.go
  go.sum
Labels: fork_required

#1434 Rework gas charging
  chain/vm/gas.go
  chain/vm/gas_v0.go
  chain/vm/runtime.go
  chain/vm/validation_test.go
  chain/vm/vm.go
  go.mod
  go.sum
Labels: fork_required

#1429 Calculate new actor addresses as per updated spec
  chain/vm/runtime.go
  chain/vm/vm.go
Labels: fork_required, in progress

#1417 take snapshot after gas transfer so its not reverted on method failure
  chain/vm/vm.go
  go.mod
  go.sum
Labels: fork_required

#1425 use proper lookback, and proper serialization for randomness generation
  build/params_shared.go
  chain/gen/gen.go
  chain/sync.go
  miner/miner.go
Labels: fork_required

#1426 Re: #1412: Add a non-blocking version of StateWaitMsg
  api/api_full.go
  api/apistruct/struct.go
  chain/stmgr/stmgr.go
  cli/state.go
  node/impl/full/state.go
  storage/miner.go
  storage/sealing/sealing.go
Labels: enhancement

#1477 Update chain-validation, enable state root validation
  chain/validation/applier.go
  chain/validation/config.go
  chain/validation/factories.go
  chain/validation/keymanager.go
  go.mod
  go.sum
Labels: blocked external
