Repository filecoin-project/lotus, pull requests merged in 2020-04, with the labels that each got.

#1523 Add info for miners who want to accept storage deals
  documentation/en/.library.json
  documentation/en/miner-deals.md
Labels: documentation

#1630 Minor / irrelevant improvements go here
  build/params_shared.go
  storage/wdpost_sched.go
Labels: in progress

#1638 fix: insufficient gas remaining to cover retval
  chain/vm/vm.go
Labels: bug
