Repository filecoin-project/lotus, pull requests merged in 2020-10, with the labels that each got.

#4122 Convert ID addresses to key addresses before checking wallet
  node/impl/client/client.go
Labels: area/client/storage

#3589 Bugfix: Runtime's Receiver() should only return ID addresses
  chain/vm/mkactor.go
  chain/vm/runtime.go
  chain/vm/vm.go
Labels: P0, area/chain/vm, impact/consensus, kind/bug

#3697 fix: error when actor panics directly
  chain/vm/runtime.go
Labels: impact/consensus

#4319 Add a CLI tool for miner's to repay debt
  chain/actors/builtin/miner/miner.go
  cmd/lotus-storage-miner/actor.go
Labels: area/ux

#4504 Miner finder for interactive client deal CLI
  cli/client.go
  go.mod
  go.sum
Labels: area/ux

#4559 Fix random test failures
  chain/sync.go
  miner/miner.go
Labels: impact/test-flakiness, kind/test

#4561 Fix flaky TestTimedBSSimple
  lib/timedbs/timedbs.go
  lib/timedbs/timedbs_test.go
Labels: impact/test-flakiness

#4600 Make EarlyExpiration in sectors list less scary
  cmd/lotus-storage-miner/sectors.go
Labels: area/ux

#4645 sectorstorage: Fix manager restart edge-case
  extern/sector-storage/manager_calltracker.go
  extern/sector-storage/manager_test.go
  extern/sector-storage/testworker_test.go
Labels: area/sealing/storage, kind/bug

#4643 storagefsm: Fix GetTicket loop when the sector is already precommitted
  extern/storage-sealing/states_sealing.go
Labels: area/sealing/fsm, kind/bug

#4669 Add sync status to miner info command
  cmd/lotus-storage-miner/info.go
Labels: area/ux
