Repository filecoin-project/lotus, pull requests merged in 2020-09, with the labels that each got.

#3442 Some more Chainwatch improvements
  cmd/lotus-chainwatch/processor/processor.go
  cmd/lotus-chainwatch/syncer/blockssub.go
  cmd/lotus-chainwatch/syncer/sync.go
Labels: kind/enhancement

#3436 fix: referenced filename
  documentation/en/api.md
Labels: topic/docs

#3526 Stop SyncIncomingBlocks from leaking into chainwatch processing; No panics during processing
  cmd/lotus-chainwatch/processor/messages.go
  cmd/lotus-chainwatch/processor/processor.go
Labels: kind/bug

#3523 paych: Create `lotus paych status` command
  cli/paych.go
  cli/paych_test.go
Labels: area/ux

#3627 Update to specs 0.9.7 and markets 0.6.0
  chain/gen/genesis/genesis.go
  chain/gen/genesis/miners.go
  chain/stmgr/call.go
  chain/stmgr/stmgr.go
  chain/stmgr/utils.go
  chain/vm/runtime.go
  chain/vm/vm.go
  go.mod
  go.sum
  node/impl/full/state.go
Labels: impact/consensus

#3546 net cli: Support miner addresses in net connect
  cli/net.go
Labels: area/ux

#3590 Multisig API additions
  api/api_full.go
  api/apistruct/struct.go
  cli/multisig.go
  documentation/en/api-methods.md
  node/impl/full/multisig.go
  node/impl/full/state.go
Labels: area/multisig, area/ux

#3670 Drand upgrade
  build/drand.go
  build/params_2k.go
  build/params_testground.go
  build/params_testnet.go
  chain/beacon/beacon.go
  chain/beacon/drand/drand.go
  chain/beacon/drand/drand_test.go
  chain/beacon/mock.go
  chain/gen/gen.go
  chain/stmgr/utils.go
  chain/sync.go
  go.mod
  go.sum
  node/builder.go
  node/impl/full/beacon.go
  node/impl/full/state.go
  node/modules/chain.go
  node/modules/core.go
  node/modules/dtypes/beacon.go
  node/modules/lp2p/pubsub.go
  node/modules/services.go
  node/modules/testing/beacon.go
  scripts/dev/sminer-init
Labels: P0

#3725 Update to specs-actors v0.9.8
  api/api_full.go
  api/apistruct/struct.go
  build/params_shared_funcs.go
  build/params_shared_vals.go
  build/params_testground.go
  chain/gen/genesis/genesis.go
  chain/gen/genesis/miners.go
  chain/stmgr/forks_test.go
  chain/stmgr/stmgr.go
  chain/stmgr/utils.go
  chain/vm/invoker.go
  chain/vm/invoker_test.go
  chain/vm/runtime.go
  chain/vm/vm.go
  conformance/chaos/actor.go
  documentation/en/api-methods.md
  go.mod
  go.sum
  node/impl/client/client.go
  node/impl/full/state.go
  storage/miner.go
  storage/wdpost_run.go
  storage/wdpost_sched.go
Labels: P0

#3874 Make interactive deal CLI reject deals shorter than minimum duration
  cli/client.go
Labels: area/ux

#3909 wdpost: Only add proven partitions to message params
  cmd/lotus-shed/bitfield.go
  storage/wdpost_run.go
Labels: kind/bug

#3953 break error
  miner/miner.go
Labels: area/mining, hint/needs-review

#3991 Make sync wait nicer
  api/api_full.go
  chain/vm/vm.go
  cli/sync.go
  documentation/en/api-methods.md
  node/impl/full/sync.go
Labels: area/ux

#3870 Add CLIs for new multisig LockBalance method
  cli/multisig.go
Labels: area/multisig, area/ux

#4009 Correct helptext
  cmd/lotus-storage-miner/market.go
Labels: area/ux

#4070 snapshot import progress bar, http support
  cmd/lotus/daemon.go
  go.mod
Labels: area/ux

#3445 Fix some failed precommit handling
  extern/storage-sealing/states_failed.go
Labels: area/sealing/fsm

#4108 Improve miner sectors list UX
  cli/client.go
  cli/util.go
  cmd/lotus-storage-miner/sectors.go
  go.mod
  go.sum
  lib/tablewriter/tablewriter.go
Labels: area/ux

#4116 sched: Allow some single-thread tasks to run in parallel with PC2/C2
  extern/sector-storage/resources.go
  extern/sector-storage/sched_resources.go
  extern/sector-storage/sched_test.go
Labels: area/sealing/storage
