Repository filecoin-project/lotus, pull requests merged in 2020-08, with the labels that each got.

#2788 fix(chainwatch): Miner partition processing panics on nil bitfiled
  cmd/lotus-chainwatch/processor/miner.go
Labels: kind/bug

#2816 Fix misspelling in HelloMessage
  node/hello/cbor_gen.go
  node/hello/hello.go
Labels: area/ux

#2784 Tighten up timestamp check
  chain/sync.go
Labels: impact/consensus-breakage

#2640 Fixes locking issues when creating channel / adding funds
  api/api_full.go
  api/apistruct/struct.go
  api/test/paych.go
  chain/vm/runtime.go
  cli/paych.go
  gen/main.go
  markets/retrievaladapter/client.go
  node/builder.go
  node/impl/paych/paych.go
  paychmgr/accessorcache.go
  paychmgr/cbor_gen.go
  paychmgr/channellock.go
  paychmgr/manager.go
  paychmgr/msglistener.go
  paychmgr/msglistener_test.go
  paychmgr/paych.go
  paychmgr/paych_test.go
  paychmgr/paychget_test.go
  paychmgr/settle_test.go
  paychmgr/simple.go
  paychmgr/state.go
  paychmgr/store.go
  paychmgr/store_test.go
Labels: area/payment-channel, goal/incentives, status/in-progress

#2885 Fix send CLI
  cli/send.go
Labels: area/ux

#2901 feat(chainwatch): track message size in bytes
  cmd/lotus-chainwatch/processor/messages.go
Labels: kind/enhancement

#2910 feat(chainwatch): capture circulating fil per tipset metric
  cmd/lotus-chainwatch/syncer/sync.go
Labels: kind/enhancement

#2958 MessagesForTipset should filter out bad nonce messages
  chain/gen/gen.go
  chain/stmgr/call.go
  chain/stmgr/stmgr.go
  chain/store/store.go
  chain/sync_test.go
  chain/validation/applier.go
Labels: impact/consensus-breakage

#2961 Revise TotalCircSupply
  chain/gen/genesis/genesis.go
  chain/gen/genesis/miners.go
  chain/stmgr/call.go
  chain/stmgr/stmgr.go
  chain/stmgr/utils.go
  chain/validation/applier.go
  chain/vm/runtime.go
  chain/vm/vm.go
  node/impl/full/state.go
Labels: hint/needs-review, impact/consensus-breakage

#2678 Check repo's genesis against baked-in genesis
  documentation/en/local-dev-net.md
  node/modules/chain.go
Labels: area/ux, status/in-progress

#2991 paych: use spec-actors paych with AMT for lane states
  go.mod
  go.sum
  paychmgr/manager.go
  paychmgr/mock_test.go
  paychmgr/paych.go
  paychmgr/paych_test.go
  paychmgr/state.go
Labels: goal/incentives

#3113 Chainwatch Improvements
  Makefile
  cmd/lotus-chainwatch/main.go
  cmd/lotus-chainwatch/processor/common_actors.go
  cmd/lotus-chainwatch/syncer/sync.go
Labels: kind/enhancement

#3127 Add a CLI method to set peerid
  cmd/lotus-storage-miner/actor.go
Labels: area/ux

#3131 strip peerid when setting on-chain addrs
  cmd/lotus-storage-miner/actor.go
Labels: area/ux

#3140 restart WaitDeals timers if miner restarts
  extern/storage-sealing/fsm.go
Labels: area/sealing/fsm

#3137 More Chainwatch Improvements
  cmd/lotus-chainwatch/processor/common_actors.go
  cmd/lotus-chainwatch/processor/processor.go
Labels: kind/enhancement

#3135 proper genesis block history
  chain/gen/gen.go
  chain/gen/genesis/genblock.go
  chain/gen/genesis/genesis.go
  chain/stmgr/stmgr.go
  chain/store/store.go
  cmd/lotus-chainwatch/syncer/sync.go
  node/impl/full/gas.go
Labels: impact/consensus-breakage

#3144 Basefee change depends on unique messages not all messages
  build/params_shared_vals.go
  build/params_testground.go
  chain/store/basefee.go
  chain/store/basefee_test.go
Labels: P1, goal/incentives, impact/consensus-breakage

#3136 Create a testnet version of setupGenesisActors
  chain/stmgr/stmgr.go
Labels: goal/incentives, impact/consensus-breakage

#3147 fsm: Config for limiting max sealing sectors
  cli/pprof.go
  cmd/lotus-storage-miner/config.go
  extern/storage-sealing/checks.go
  extern/storage-sealing/fsm.go
  extern/storage-sealing/fsm_events.go
  extern/storage-sealing/fsm_test.go
  extern/storage-sealing/garbage.go
  extern/storage-sealing/sealiface/config.go
  extern/storage-sealing/sealing.go
  extern/storage-sealing/sector_state.go
  extern/storage-sealing/states_failed.go
  extern/storage-sealing/states_sealing.go
  extern/storage-sealing/stats.go
  extern/storage-sealing/types.go
  node/builder.go
  node/config/def.go
  node/impl/storminer.go
  node/modules/dtypes/miner.go
  node/modules/storageminer.go
  storage/adapter_storage_miner.go
  storage/miner.go
Labels: goal/incentives

#3138 place the remainder of unallocated funds in a 'remainder' account
  chain/gen/gen.go
  chain/gen/genesis/genesis.go
  chain/gen/genesis/t01_init.go
  chain/stmgr/stmgr.go
  cmd/lotus-seed/genesis.go
  genesis/types.go
  node/node_test.go
Labels: goal/incentives

#3160 cc upgrade fixes
  extern/storage-sealing/states_sealing.go
  extern/storage-sealing/upgrade_queue.go
Labels: area/sealing/fsm

#3181 Do not try to replace CC sectors with a deal-less sector
  extern/storage-sealing/upgrade_queue.go
Labels: area/sealing/fsm

#3185 fix(chainwatch): Handle RewardState.EpochSmoothingEstimate == nil
  cmd/lotus-chainwatch/processor/reward.go
Labels: kind/bug

#3200 Update links
  CHANGELOG.md
  README.md
  cmd/lotus-fountain/site/_miner.html
  documentation/en/dev-tools-pond-ui.md
  documentation/en/dev/create-miner.md
  documentation/en/faqs.md
  documentation/en/getting-started.md
  documentation/en/install-lotus-arch.md
  documentation/en/install-lotus-fedora.md
  documentation/en/install-lotus-macos.md
  documentation/en/install-lotus-ubuntu.md
  documentation/en/join-testnet.md
  documentation/en/mining-lotus-worker.md
  documentation/en/mining-troubleshooting.md
  documentation/en/mining.md
  documentation/en/retrieving-data.md
  documentation/en/storing-data-troubleshooting.md
Labels: topic/docs

#3122 sorted deal listings
  api/api_full.go
  cli/client.go
  cmd/lotus-storage-miner/market.go
  go.mod
  go.sum
  node/impl/client/client.go
Labels: status/deferred

#3250 miner info: Fix avail calc, print aggregate deal info
  cmd/lotus-storage-miner/info.go
  go.sum
Labels: area/ux

#3259 Bugfix: fix some typo and correct recoveries datasource
  cmd/lotus-storage-miner/proving.go
Labels: status/done

#3330 print block 'age' when validating blocks during sync
  chain/sync.go
Labels: area/ux

#3367 feat(chainwatch): Add more complete power and reward metrics
  cmd/lotus-chainwatch/processor/power.go
  cmd/lotus-chainwatch/processor/reward.go
  cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
  cmd/lotus-chainwatch/syncer/sync.go
Labels: kind/enhancement

#3401 Rebuild unsealed infos on miner restart
  extern/storage-sealing/fsm.go
Labels: area/sealing/fsm
