Repository filecoin-project/lotus, pull requests merged in 2020-07, with the labels that each got.

#2227 Add docs comments to API
  api/api_full.go
  chain/stmgr/utils.go
Labels: api, documentation

#2260 Add CLI command to manually start sealing a sector
  cmd/lotus-storage-miner/sectors.go
  go.sum
Labels: cli, ux

#2302 Minor CLI improvements
  cli/client.go
  cli/multisig.go
  cli/state.go
Labels: cli, ux

#2377 API improvements
  api/api_full.go
  api/apistruct/struct.go
  build/version.go
  cli/multisig.go
  cli/state.go
  node/impl/full/multisig.go
  node/impl/full/state.go
  storage/adapter_storage_miner.go
Labels: api, cli

#2398 clarify multisig create helptext
  cli/multisig.go
Labels: cli, ux

#2381 Add a FAQ
  documentation/en/faqs.md
Labels: documentation

#2430 SwapSigner API methods
  api/api_full.go
  api/apistruct/struct.go
  cli/multisig.go
  cli/send.go
  node/impl/full/multisig.go
Labels: api, cli

#2443 Capture base block rewards
  cmd/lotus-chainwatch/dot.go
  cmd/lotus-chainwatch/main.go
  cmd/lotus-chainwatch/processor/common_actors.go
  cmd/lotus-chainwatch/processor/market.go
  cmd/lotus-chainwatch/processor/messages.go
  cmd/lotus-chainwatch/processor/miner.go
  cmd/lotus-chainwatch/processor/processor.go
  cmd/lotus-chainwatch/processor/reward.go
  cmd/lotus-chainwatch/run.go
  cmd/lotus-chainwatch/syncer/sync.go
Labels: enhancement

#2429 feat: track miner precommit
  chain/events/state/diff_adt.go
  chain/events/state/predicates.go
  cmd/lotus-chainwatch/processor/miner.go
  cmd/lotus-chainwatch/processor/processor.go
Labels: in progress

#2489 Restore base block reward; capture WinCount w header
  cmd/lotus-chainwatch/processor/reward.go
  cmd/lotus-chainwatch/syncer/sync.go
Labels: bug

#2501 fix: use bigint for gas_used in message receipt
  cmd/lotus-chainwatch/processor/messages.go
Labels: bug

#2543 update devnet in readme
  README.md
Labels: documentation

#2542 feat(chainwatch): Ticker triggers view refresh independent of processing
  cmd/lotus-chainwatch/run.go
  cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
  cmd/lotus-chainwatch/scheduler/scheduler.go
Labels: enhancement

#2538 fix: handle reorgs for id mapping table
  cmd/lotus-chainwatch/processor/common_actors.go
Labels: bug

#2550 fix: correctly pass variadic args from runtime log
  chain/vm/runtime.go
Labels: bug

#2506 API documentation must not tell lies
  api/api_full.go
Labels: api, documentation

#2584 Top Miner by Reward applies WinCount; Add max_height view
  cmd/lotus-chainwatch/processor/reward.go
  cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
  cmd/lotus-chainwatch/scheduler/scheduler.go
Labels: bug, enhancement

#2598 CLI: Optionally include vesting details in msig inspect
  cli/multisig.go
Labels: cli, ux

#2615 fix: Chainwatch handle null rounds
  cmd/lotus-chainwatch/processor/processor.go
  cmd/lotus-chainwatch/processor/reward.go
Labels: bug

#2674 Include listen addresses in CLI miner info
  cli/state.go
  cmd/lotus-storage-miner/actor.go
Labels: area/ux
