Repository filecoin-project/lotus, pull requests merged in 2020-06, with the labels that each got.

#1884 fountain/miner: Add a link to docs about creating owner address
  cmd/lotus-fountain/site/miner.html
Labels: ux

#1924 Sealing Improvements
  api/api_worker.go
  api/apistruct/struct.go
  cmd/lotus-seal-worker/main.go
  cmd/lotus-storage-miner/info.go
  go.mod
  go.sum
  node/impl/storminer.go
  storage/adapter_storage_miner.go
Labels: sealing, ux

#1947 Correct double-counting in StateMinerAvailableBalance
  node/impl/full/state.go
Labels: bug

#1946 Add delete functionality to the wallet
  api/api_full.go
  api/apistruct/struct.go
  chain/wallet/wallet.go
  cli/wallet.go
  node/impl/full/wallet.go
Labels: ux

#1927 Express block validation time via OpenCensus
  chain/sync.go
  cmd/lotus/daemon.go
  metrics/metrics.go
Labels: enhancement

#1959 display quantities of bytes in human-readable format
  cli/chain.go
  cli/client.go
  cli/state.go
Labels: ux

#1768 Lotus architecture notes
  chain/sync.go
  chain/sync_manager.go
  documentation/en/.library.json
  documentation/en/architecture.md
  documentation/en/dev/WIP-arch-complementary-notes.md
Labels: documentation

#1965 Doc fix: use correct file name
  documentation/en/.library.json
Labels: documentation

#2001 Improve UX of fetch-params
  .circleci/config.yml
  cli/params.go
  documentation/en/local-dev-net.md
Labels: cli, ux

#2065 docgen improvements
  api/api_common.go
  api/api_full.go
  api/docgen/docgen.go
  build/params_testnet.go
Labels: documentation

#2094 doc: report a vulnerability
  README.md
  SECURITY.md
Labels: documentation, security

#2093 Clarify expected block win when below minimum power threshold
  cmd/lotus-storage-miner/info.go
Labels: ux

#2050 Return sector numbers, not bitfields from API
  api/api_full.go
  api/apistruct/struct.go
  build/version.go
  cli/state.go
  cmd/lotus-chainwatch/sync.go
  go.mod
  go.sum
  node/impl/full/state.go
Labels: api

#1919 doc: block validations
  chain/types/message.go
  documentation/en/block-validation.md
Labels: documentation, security
