Repository filecoin-project/lotus, pull requests merged in 2020-12, with the labels that each got.

#5083 miner info cli improvements
  chain/types/fil.go
  chain/types/fil_test.go
  cmd/lotus-storage-miner/info.go
Labels: area/mining, area/ux

#5200 Disable gas burning for window post messages
  build/params_2k.go
  build/params_mainnet.go
  build/params_testground.go
  chain/vm/burn.go
  chain/vm/burn_test.go
  chain/vm/vm.go
Labels: impact/consensus

#5182 fix(sync): enforce ForkLengthThreshold for synced chain
  chain/sync.go
Labels: area/chain/sync, impact/consensus
