Repository filecoin-project/lotus, pull requests merged in 2021-09, with the labels that each got.

#7245 sealing: Fix retry loop in SubmitCommitAggregate
  extern/storage-sealing/fsm.go
  extern/storage-sealing/fsm_test.go
  extern/storage-sealing/states_sealing.go
Labels: kind/bug, area/sealing

#7256 sealing: Fix sector state accounting with FinalizeEarly
  extern/storage-sealing/sector_state.go
  extern/storage-sealing/stats.go
Labels: area/sealing

#7253 update to go-fil-markets v1.11.0
  go.mod
  go.sum
Labels: P1

#7197 Update to unified go-graphsync v0.9.0
  api/docgen/docgen.go
  go.mod
  go.sum
  node/modules/graphsync.go
  node/modules/storageminer.go
Labels: P1, blocked

#7276 introduce MaxStagingDealsBytes - reject new deals if our staging deals area is full
  .circleci/config.yml
  itests/deals_max_staging_deals_test.go
  itests/kit/deals.go
  itests/kit/ensemble.go
  itests/kit/node_opts.go
  node/builder_miner.go
  node/config/doc_gen.go
  node/config/types.go
  node/modules/storageminer.go
Labels: P2

#7336 fix a panic in HandleRecoverDealIDs
  extern/storage-sealing/states_failed.go
Labels: release/backport

#7346 GetCurrentDealInfo err: handle correctly err case
  extern/storage-sealing/states_failed.go
  extern/storage-sealing/states_failed_test.go
Labels: release/backport

#7376 Fix Drand fetching around null tipsets
  chain/beacon/mock.go
  chain/consensus/filcns/compute_state.go
  chain/consensus/filcns/filecoin.go
  chain/gen/gen.go
  chain/gen/genesis/miners.go
  chain/rand/rand.go
  chain/rand/rand_test.go
  chain/stmgr/actors.go
  chain/stmgr/call.go
  chain/stmgr/forks_test.go
  chain/stmgr/stmgr.go
  chain/stmgr/utils.go
  chain/store/rand.go
  chain/store/store.go
  chain/store/store_test.go
  chain/sync_test.go
  chain/vm/runtime.go
  chain/vm/vm.go
  cmd/lotus-bench/import.go
  cmd/lotus-shed/balances.go
  cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go
  cmd/lotus-sim/simulation/node.go
  cmd/lotus-sim/simulation/simulation.go
  cmd/lotus-sim/simulation/stages/util.go
  cmd/lotus/daemon.go
  conformance/driver.go
  conformance/rand_fixed.go
  conformance/rand_record.go
  conformance/rand_replay.go
  miner/miner.go
  node/impl/full/state.go
  node/modules/chain.go
  node/modules/stmgr.go
Labels: P0
