Repository filecoin-project/lotus, pull requests merged in 2021-06, with the labels that each got.

#6337 Add a command to list retrievals
  api/api_full.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  api/types.go
  api/v0api/full.go
  api/v0api/proxy_gen.go
  api/v0api/v0mocks/mock_full.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cli/client.go
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  documentation/en/cli-lotus.md
  node/impl/client/client.go
Labels: P2, area/api, impact/docs

#5921 Fix success handling in Retreival
  cli/client.go
Labels: x/ignite

#6081 Integration tests for offline deals
  api/test/deals.go
  node/node_test.go
Labels: x/ignite

#6280 Bypass task scheduler for reading unsealed pieces
  .circleci/config.yml
  api/api_worker.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  api/test/deals.go
  api/v0api/v0mocks/mock_full.go
  api/version.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cli/servicesmock_test.go
  cmd/lotus-seal-worker/main.go
  cmd/lotus-storage-miner/init.go
  documentation/en/api-v0-methods-worker.md
  extern/sector-storage/ffiwrapper/sealer_cgo.go
  extern/sector-storage/ffiwrapper/unseal_ranges.go
  extern/sector-storage/fr32/readers.go
  extern/sector-storage/manager.go
  extern/sector-storage/manager_test.go
  extern/sector-storage/mock/mock.go
  extern/sector-storage/partialfile/partialfile.go
  extern/sector-storage/piece_provider.go
  extern/sector-storage/piece_provider_test.go
  extern/sector-storage/resources.go
  extern/sector-storage/sealtasks/task.go
  extern/sector-storage/stores/http_handler.go
  extern/sector-storage/stores/http_handler_test.go
  extern/sector-storage/stores/interface.go
  extern/sector-storage/stores/mocks/index.go
  extern/sector-storage/stores/mocks/stores.go
  extern/sector-storage/stores/remote.go
  extern/sector-storage/stores/remote_test.go
  extern/sector-storage/stores/util_unix.go
  extern/sector-storage/storiface/ffi.go
  extern/sector-storage/storiface/worker.go
  extern/sector-storage/worker_local.go
  extern/sector-storage/worker_tracked.go
  go.mod
  go.sum
  markets/retrievaladapter/provider.go
  node/builder.go
  node/impl/remoteworker.go
  node/modules/storageminer.go
  node/test/builder.go
Labels: x/ignite

#6419 Increase message size limit
  chain/messagepool/messagepool.go
  chain/messagepool/messagepool_test.go
Labels: release/backport

#6420 Fee config for sector batching
  extern/storage-sealing/commit_batch.go
  extern/storage-sealing/precommit_batch.go
  extern/storage-sealing/sealing.go
  extern/storage-sealing/states_sealing.go
  extern/storage-sealing/terminate_batch.go
  node/config/def.go
  storage/miner.go
Labels: release/backport

#6416 Commit and Precommit batcher cannot share a getSectorDeadline method
  build/params_nerpanet.go
  extern/storage-sealing/commit_batch.go
  extern/storage-sealing/precommit_batch.go
Labels: release/backport

#6441 Set ntwk v13 HyperDrive Calibration upgrade epoch
  build/params_calibnet.go
Labels: release/backport

#6440 updated configuration comments for docs
  node/config/def.go
Labels: release/backport

#6311 consolidate integration tests into `itests` package; create test kit; cleanup
  api/test/blockminer.go
  api/test/deals.go
  api/test/mining.go
  api/test/pledge.go
  api/test/test.go
  api/test/util.go
  api/test/window_post.go
  cli/client_test.go
  cli/multisig_test.go
  cli/test/util.go
  cmd/lotus-gateway/main.go
  cmd/lotus-storage-miner/actor_test.go
  cmd/lotus-storage-miner/allinfo_test.go
  cmd/lotus-storage-miner/run.go
  cmd/lotus/daemon.go
  cmd/lotus/main.go
  cmd/lotus/pprof.go
  cmd/lotus/rpc.go
  gateway/handler.go
  itests/api_test.go
  itests/batch_deal_test.go
  itests/ccupgrade_test.go
  itests/cli_test.go
  itests/deadlines_test.go
  itests/deals_test.go
  itests/doc.go
  itests/gateway_test.go
  itests/kit/blockminer.go
  itests/kit/client.go
  itests/kit/deals.go
  itests/kit/funds.go
  itests/kit/init.go
  itests/kit/log.go
  itests/kit/mockcli.go
  itests/kit/net.go
  itests/kit/node_builder.go
  itests/kit/nodes.go
  itests/kit/pledge.go
  itests/multisig_test.go
  itests/paych_api_test.go
  itests/paych_cli_test.go
  itests/sdr_upgrade_test.go
  itests/sector_pledge_test.go
  itests/sector_terminate_test.go
  itests/tape_test.go
  itests/verifreg_test.go
  itests/wdpost_dispute_test.go
  itests/wdpost_test.go
  node/hello/hello.go
  node/node_test.go
  node/rpc.go
  node/shutdown.go
  node/shutdown_test.go
  paychmgr/settler/settler.go
Labels: x/ignite

#6451 clean failed sectors in batch commit
  extern/storage-sealing/commit_batch.go
Labels: release/backport

#6465 Update chain list with correct help instructions
  cli/chain.go
Labels: area/ux

#6309 Adjust various CLI display ratios to arbitrary precision
  chain/types/bigint.go
  cli/state.go
  cmd/lotus-shed/sync.go
  cmd/lotus-storage-miner/info.go
  cmd/lotus-storage-miner/proving.go
  testplans/lotus-soup/rfwp/chain_state.go
Labels: P3

#6175 Dynamic Retrieval pricing
  cmd/lotus-storage-miner/allinfo_test.go
  cmd/lotus-storage-miner/retrieval-deals.go
  documentation/en/cli-lotus-miner.md
  extern/sector-storage/mock/mock.go
  extern/sector-storage/piece_provider.go
  extern/sector-storage/piece_provider_test.go
  extern/sector-storage/stores/remote.go
  extern/sector-storage/stores/remote_test.go
  go.mod
  go.sum
  itests/ccupgrade_test.go
  itests/deals_test.go
  itests/gateway_test.go
  itests/kit/deals.go
  markets/pricing/cli.go
  markets/retrievaladapter/provider.go
  markets/retrievaladapter/provider_test.go
  node/builder.go
  node/config/def.go
  node/modules/dtypes/miner.go
  node/modules/storageminer.go
Labels: P1, x/ignite

#6521 fix commit finalize failed
  extern/storage-sealing/fsm.go
  extern/storage-sealing/fsm_test.go
Labels: release/backport

#6329 revamped integration test kit (aka. Operation Sparks Joy)
  .circleci/config.yml
  cmd/lotus-storage-miner/actor_test.go
  cmd/lotus-storage-miner/allinfo_test.go
  itests/api_test.go
  itests/batch_deal_test.go
  itests/ccupgrade_test.go
  itests/cli_test.go
  itests/deadlines_test.go
  itests/deals_concurrent_test.go
  itests/deals_offline_test.go
  itests/deals_power_test.go
  itests/deals_pricing_test.go
  itests/deals_publish_test.go
  itests/deals_test.go
  itests/gateway_test.go
  itests/kit/blockminer.go
  itests/kit/client.go
  itests/kit/deals.go
  itests/kit/deals_state.go
  itests/kit/ensemble.go
  itests/kit/ensemble_opts.go
  itests/kit/ensemble_presets.go
  itests/kit/files.go
  itests/kit/funds.go
  itests/kit/init.go
  itests/kit/log.go
  itests/kit/net.go
  itests/kit/node_builder.go
  itests/kit/node_full.go
  itests/kit/node_miner.go
  itests/kit/node_opts.go
  itests/kit/node_opts_nv.go
  itests/kit/nodes.go
  itests/kit/pledge.go
  itests/kit/rpc.go
  itests/multisig/suite.go
  itests/multisig_test.go
  itests/paych_api_test.go
  itests/paych_cli_test.go
  itests/sdr_upgrade_test.go
  itests/sector_pledge_test.go
  itests/sector_terminate_test.go
  itests/tape_test.go
  itests/verifreg_test.go
  itests/wdpost_dispute_test.go
  itests/wdpost_test.go
Labels: x/ignite

#6634 remove precommit check in handleCommitFailed
  extern/storage-sealing/states_failed.go
Labels: release/backport
