Repository filecoin-project/lotus, pull requests merged in 2021-08, with the labels that each got.

#6909 add explicit error msg if repo dir does not exist
  cli/util/api.go
Labels: P2, release/backport, x/ignite

#6967 lotus-shed splitstore clear command
  blockstore/splitstore/README.md
  cmd/lotus-shed/splitstore.go
Labels: M1-release, P2, epic/splitstore, release/backport, x/ignite

#6949 Reduce splitstore memory usage during chain walks
  blockstore/splitstore/markset.go
  blockstore/splitstore/markset_badger.go
  blockstore/splitstore/markset_bloom.go
  blockstore/splitstore/markset_map.go
  blockstore/splitstore/markset_test.go
  blockstore/splitstore/splitstore.go
  blockstore/splitstore/splitstore_check.go
  blockstore/splitstore/splitstore_compact.go
  blockstore/splitstore/splitstore_warmup.go
  blockstore/splitstore/visitor.go
Labels: x/ignite, epic/splitstore

#7007 Dont panic if input is bad
  chain/actors/policy/policy.go
  chain/actors/policy/policy.go.template
  chain/actors/version.go
  chain/gen/genesis/genesis.go
  chain/gen/genesis/miners.go
  chain/vm/invoker.go
  chain/vm/mkactor.go
  cmd/lotus-miner/sectors.go
  cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go
  cmd/lotus-sim/simulation/stages/funding_stage.go
  cmd/lotus-sim/simulation/stages/provecommit_stage.go
  extern/storage-sealing/commit_batch.go
  extern/storage-sealing/states_sealing.go
  node/impl/full/multisig.go
  node/impl/full/state.go
  paychmgr/paych.go
  storage/wdpost_run.go
Labels: P3, tribute

#7022 revert pricelist by version to pricelist by epoch
  api/version.go
  build/openrpc/full.json.gz
  build/openrpc/worker.json.gz
  build/params_2k.go
  build/params_butterfly.go
  build/params_calibnet.go
  build/params_interop.go
  build/params_mainnet.go
  build/params_nerpanet.go
  build/params_testground.go
  chain/actors/version.go
  chain/messagepool/check.go
  chain/messagepool/messagepool.go
  chain/messagepool/selection.go
  chain/stmgr/upgrades.go
  chain/sync.go
  chain/vm/gas.go
  chain/vm/mkactor.go
  chain/vm/vm.go
  documentation/en/api-v0-methods-miner.md
  documentation/en/api-v0-methods-worker.md
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  go.mod
  go.sum
Labels: release/backport

#7042 make `lotus-miner net` commands hit markets subsystem.
  cli/cmd.go
  cmd/lotus-miner/main.go
Labels: release/backport, M1-release

#7079 clean up car handling, IPFS integration, import manager, retrieve RPC.
  api/api_full.go
  build/openrpc/full.json.gz
  cli/client.go
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  go.mod
  go.sum
  markets/retrievaladapter/client_blockstore.go
  markets/storageadapter/client_blockstore.go
  node/builder.go
  node/builder_chain.go
  node/impl/client/car_helpers.go
  node/impl/client/client.go
  node/impl/client/client_test.go
  node/impl/client/import.go
  node/impl/client/import_test.go
  node/impl/client/testdata/duplicate_blocks.txt
  node/impl/client/testdata/payload.txt
  node/impl/client/testdata/payload2.txt
  node/modules/client.go
  node/modules/dtypes/storage.go
  node/modules/graphsync.go
  node/modules/ipfs.go
  node/repo/imports/manager.go
  node/repo/retrievalstoremgr/retrievalstoremgr.go
Labels: x/ignite, epic/sharded-dag-store

#6097 Extending sectors: more practical and flexible tools
  cmd/lotus-miner/sectors.go
  documentation/en/cli-lotus-miner.md
Labels: P2

#6853 feat(miner deals): create subdir to miner repo for staged deals
  cmd/lotus-miner/init.go
  node/modules/storageminer.go
  node/repo/memrepo.go
Labels: P2

#6952 rpcenc: Support reader redirect
  lib/rpcenc/reader.go
  lib/rpcenc/reader_test.go
Labels: P2, x/ignite, M1-release

#7117 sealing: Fix RecoverDealIDs loop with changed PieceCID
  extern/storage-sealing/checks.go
  extern/storage-sealing/fsm.go
  extern/storage-sealing/mocks/api.go
  extern/storage-sealing/mocks/statemachine.go
  extern/storage-sealing/sealing.go
  extern/storage-sealing/states_failed.go
  extern/storage-sealing/states_failed_test.go
  extern/storage-sealing/states_proving.go
  extern/storage-sealing/states_sealing.go
  extern/storage-sealing/types.go
  extern/storage-sealing/upgrade_queue.go
Labels: P2

#7140 miner: Command to list/remove expired sectors
  chain/actors/builtin/miner/actor.go.template
  chain/actors/builtin/miner/miner.go
  cmd/lotus-miner/sectors.go
  documentation/en/cli-lotus-miner.md
Labels: kind/feature, area/mining

#7176 test: disable flaky TestBatchDealInput
  itests/batch_deal_test.go
Labels: Lotus - Internal improvements

#7173 fix TestDealPublisher
  markets/storageadapter/dealpublisher.go
Labels: Lotus - Internal improvements

#7174 fix: make TestTimedCacheBlockstoreSimple pass reliably
  blockstore/timed.go
Labels: Lotus - Internal improvements

#7208 upgrade go-data-transfer; propagate deal cancellations.
  go.mod
  go.sum
Labels: x/ignite, release/backport
