Repository filecoin-project/lotus, pull requests merged in 2021-07, with the labels that each got.

#6647 commit batch: Initialize the FailedSectors map
  extern/storage-sealing/commit_batch.go
Labels: release/backport

#6650 commit batch: AggregateAboveBaseFee config
  chain/types/fil.go
  extern/storage-sealing/commit_batch.go
  extern/storage-sealing/commit_batch_test.go
  extern/storage-sealing/sealiface/config.go
  node/config/def.go
  node/modules/storageminer.go
Labels: release/backport

#6635 fix ticket expiration check
  extern/storage-sealing/states_sealing.go
Labels: release/backport

#6658 Fix: precommit_batch method used the wrong cfg.CommitBatchWait
  extern/storage-sealing/precommit_batch.go
Labels: release/backport

#5950 add election backtest
  cmd/lotus-shed/election.go
Labels: P3

#6066 Fix bugs in sectors extend --v1-sectors
  cmd/lotus-storage-miner/sectors.go
Labels: P2

#6629 Config for collateral from miner available balance
  .circleci/config.yml
  extern/storage-sealing/commit_batch.go
  extern/storage-sealing/mocks/mock_commit_batcher.go
  extern/storage-sealing/mocks/mock_precommit_batcher.go
  extern/storage-sealing/precommit_batch.go
  extern/storage-sealing/sealiface/config.go
  extern/storage-sealing/sealing.go
  extern/storage-sealing/states_sealing.go
  extern/storage-sealing/utils.go
  itests/deals_pricing_test.go
  itests/sector_miner_collateral_test.go
  node/config/def.go
  node/modules/storageminer.go
  storage/adapter_storage_miner.go
  storage/miner.go
Labels: docs-needed

#6642 Add ChainGetMessagesInTipset API
  .circleci/config.yml
  api/api_full.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  api/v0api/full.go
  api/v0api/proxy_gen.go
  api/v0api/v0mocks/mock_full.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  itests/get_messages_in_ts_test.go
  node/impl/full/chain.go
Labels: hint/needs-author-input

#6762 Implement exposed splitstore
  blockstore/splitstore/splitstore_expose.go
  node/builder.go
  node/modules/blockstore.go
Labels: epic/splitstore, x/ignite

#6805 fix: on randomness change, use new rand
  storage/wdpost_run.go
Labels: P1

#5183 easy way to make install app
  Makefile
Labels: P3

#6837 Nerpa v13 upgrade
  build/params_nerpanet.go
Labels: release/backport

#6833 Splitstore: support on-disk marksets using badger
  blockstore/splitstore/README.md
  blockstore/splitstore/markset.go
  blockstore/splitstore/markset_badger.go
  blockstore/splitstore/markset_test.go
  blockstore/splitstore/splitstore.go
  blockstore/splitstore/splitstore_compact.go
  blockstore/splitstore/splitstore_test.go
Labels: epic/splitstore, x/ignite

#6811 splitstore shed utils
  api/api_full.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  blockstore/badger/blockstore.go
  blockstore/blockstore.go
  blockstore/splitstore/README.md
  blockstore/splitstore/splitstore.go
  blockstore/splitstore/splitstore_check.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cmd/lotus-shed/main.go
  cmd/lotus-shed/splitstore.go
  documentation/en/api-v1-unstable-methods.md
  node/impl/full/chain.go
Labels: epic/splitstore, x/ignite

#6867 Improve splitstore warmup
  blockstore/splitstore/splitstore_test.go
  blockstore/splitstore/splitstore_warmup.go
Labels: epic/splitstore, x/ignite

#6862 fix racy TestSimultanenousTransferLimit.
  itests/deals_concurrent_test.go
Labels: P1

#6674 Bump go-multihash, adjust test for supported version
  chain/events/state/predicates_test.go
  go.mod
  go.sum
Labels: P3

#6879 Add github actions for staled pr
  .github/workflows/stale.yml
Labels: P2

#6854 Moving GC for badger
  blockstore/badger/blockstore.go
  blockstore/badger/blockstore_test.go
  blockstore/blockstore.go
  blockstore/splitstore/README.md
  blockstore/splitstore/splitstore.go
  blockstore/splitstore/splitstore_gc.go
  cmd/lotus-shed/pruning.go
  node/config/def.go
  node/config/doc_gen.go
  node/config/types.go
  node/modules/blockstore.go
Labels: P2, epic/splitstore, x/ignite

#6880 Update RELEASE_ISSUE_TEMPLATE.md
  documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Labels: P2, TPM

#6840 lotus-shed: initial export cmd for markets related metadata
  cmd/lotus-shed/market.go
Labels: P2, epic/MRA, x/ignite

#6889 Reduce entropy in the chain package
  chain/gen/gen.go
  chain/gen/genesis/genesis.go
  chain/gen/genesis/miners.go
  chain/stmgr/actors.go
  chain/stmgr/call.go
  chain/stmgr/execute.go
  chain/stmgr/forks.go
  chain/stmgr/forks_test.go
  chain/stmgr/read.go
  chain/stmgr/searchwait.go
  chain/stmgr/stmgr.go
  chain/stmgr/supply.go
  chain/stmgr/upgrades.go
  chain/stmgr/utils.go
  chain/store/index_test.go
  chain/store/messages.go
  chain/store/rand.go
  chain/store/snapshot.go
  chain/store/store.go
  chain/store/store_test.go
  chain/vm/invoker.go
  chain/vm/vm.go
  cmd/lotus-bench/import.go
  cmd/lotus-shed/balances.go
  cmd/lotus-shed/export.go
  cmd/lotus-shed/genesis-verify.go
  cmd/lotus-shed/miner-types.go
  cmd/lotus-shed/pruning.go
  cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go
  cmd/lotus-sim/simulation/node.go
  cmd/lotus-sim/simulation/simulation.go
  cmd/lotus/daemon.go
  conformance/driver.go
  node/modules/chain.go
  node/modules/stmgr.go
Labels: P2

#6906 adding an RuntimeSubsystems API to storage miner; fix `lotus-miner info`
  api/api_storage.go
  api/docgen/docgen.go
  api/miner_subsystems.go
  api/proxy_gen.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cmd/lotus-miner/info.go
  documentation/en/api-v0-methods-miner.md
  node/builder_miner.go
  node/impl/storminer.go
  node/modules/storageminer.go
Labels: M1-release, P1, release/backport, x/ignite

#6919 Update to branches with improved logging
  go.mod
  go.sum
Labels: release/backport

#6895 Eliminate inefficiency in markets logging
  markets/loggers/loggers.go
Labels: release/backport

#6905 Moving GC Followup
  blockstore/badger/blockstore.go
  blockstore/badger/blockstore_test.go
Labels: M1-release, P2, epic/splitstore, release/backport, x/ignite

#6937 Update deps for more logging in data transfer and markets
  go.mod
  go.sum
Labels: release/backport, x/ignite

#6941 Update state machine deps for logging
  go.mod
  go.sum
Labels: M1-release, release/backport, x/ignite

#6936 support MARKETS_API_INFO env var, and markets-repo, markets-api-url CLI flags.
  cli/auth.go
  cli/cmd.go
  cli/util/api.go
  cmd/lotus-miner/info.go
  cmd/lotus-miner/init_restore.go
  cmd/lotus-miner/init_service.go
  cmd/lotus-miner/main.go
  cmd/lotus-miner/market.go
  cmd/lotus-miner/retrieval-deals.go
  documentation/en/cli-lotus-miner.md
  node/repo/fsrepo.go
Labels: M1-release, epic/MRA, release/backport, x/ignite

#6099 reasonable max value for initial sector expiration
  extern/storage-sealing/states_sealing.go
Labels: P2
