Repository filecoin-project/lotus, pull requests merged in 2021-03, with the labels that each got.

#5666 Command to extend sector expiration
  cmd/lotus-storage-miner/sectors.go
Labels: area/sealing

#5620 miner: Config to disable owner/worker address fallback
  api/api_storage.go
  cmd/lotus-storage-miner/actor.go
  documentation/en/api-methods-miner.md
  node/config/def.go
  node/modules/storageminer.go
  storage/addresses.go
Labels: area/mining

#5783 storagefsm: Fix double unlock with ready WaitDeals sectors
  extern/storage-sealing/input.go
Labels: area/sealing, kind/bug

#5693 Implement Event observer and Settings for 3rd party dep injection
  chain/events/events.go
  node/builder.go
Labels: area/api, kind/feature

#5814 chore: add available options for perm on error
  cli/auth.go
Labels: area/ux

#5853 update to markets v1.2.x
  go.mod
  go.sum
  node/modules/client.go
  node/modules/storageminer.go
Labels: x/ignite
