Repository filecoin-project/lotus, pull requests merged in 2021-12, with the labels that each got.

#7707 Disable appimage
  .circleci/config.yml
  .circleci/template.yml
Labels: release/backport

#7734 SplitStore: supress compaction near upgrades
  blockstore/splitstore/splitstore.go
  blockstore/splitstore/splitstore_compact.go
  blockstore/splitstore/splitstore_test.go
  node/modules/chain.go
Labels: epic/splitstore

#7737 dagstore pieceReader: Always read full in ReadAt
  go.mod
  go.sum
  markets/dagstore/mount_test.go
  markets/dagstore/piecereader.go
  metrics/metrics.go
Labels: release/backport

#7751 dep/fix 7701 Dependency: update to ipld-legacy to v0.1.1
  go.mod
  go.sum
Labels: release/backport

#7746 Make retrieval even faster
  extern/sector-storage/fr32/fr32.go
  extern/sector-storage/fr32/readers.go
  extern/sector-storage/mock/mock.go
  extern/sector-storage/piece_provider.go
  extern/sector-storage/piece_provider_test.go
  extern/sector-storage/piece_reader.go
  extern/sector-storage/stores/http_handler.go
  extern/sector-storage/stores/remote.go
  extern/sector-storage/stores/remote_test.go
  markets/dagstore/miner_api.go
  markets/dagstore/miner_api_test.go
  markets/dagstore/mocks/mock_lotus_accessor.go
  markets/dagstore/mount.go
  markets/dagstore/mount_test.go
  markets/dagstore/wrapper_migration_test.go
  markets/dagstore/wrapper_test.go
  markets/sectoraccessor/sectoraccessor.go
Labels: release/backport

#7321 Mempool msg selection should respect block message limits
  chain/consensus/filcns/mine.go
  chain/messagepool/repub.go
  chain/messagepool/selection.go
  chain/messagepool/selection_test.go
Labels: P1

#7578 feat(graphsync): allow setting of per-peer incoming requests for miners
  documentation/en/default-lotus-miner-config.toml
  itests/deals_concurrent_test.go
  node/builder_miner.go
  node/config/def.go
  node/config/doc_gen.go
  node/config/types.go
  node/modules/storageminer.go
  tools/packer/repo/config.toml
Labels: P2
