Repository filecoin-project/lotus, pull requests merged in 2022-02, with the labels that each got.

#8022 update go-libp2p to v0.18.0-rc3
  go.mod
  go.sum
Labels: release/backport

#8021 add net protect api methods
  api/api_net.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  api/v0api/v0mocks/mock_full.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  documentation/en/api-v0-methods-miner.md
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  documentation/en/default-lotus-miner-config.toml
  node/impl/net/protect.go
Labels: impact/new-api

#7905 StartEpochSealingBuffer triggers packing on timer
  documentation/en/default-lotus-miner-config.toml
  extern/storage-sealing/input.go
  extern/storage-sealing/sealiface/config.go
  node/config/def.go
  node/config/doc_gen.go
  node/config/types.go
  node/modules/storageminer.go
Labels: docs-needed

#8008 splitstore sortless compaction
  blockstore/splitstore/README.md
  blockstore/splitstore/checkpoint.go
  blockstore/splitstore/checkpoint_test.go
  blockstore/splitstore/coldset.go
  blockstore/splitstore/coldset_test.go
  blockstore/splitstore/markset.go
  blockstore/splitstore/markset_badger.go
  blockstore/splitstore/markset_map.go
  blockstore/splitstore/markset_test.go
  blockstore/splitstore/splitstore.go
  blockstore/splitstore/splitstore_check.go
  blockstore/splitstore/splitstore_compact.go
  blockstore/splitstore/splitstore_test.go
  blockstore/splitstore/splitstore_warmup.go
  documentation/en/default-lotus-config.toml
  node/config/def.go
  node/config/doc_gen.go
  node/config/types.go
Labels: P1

#8090 fix: worker: allow enable/disabling ReplicaUpdate tasks
  cmd/lotus-miner/init.go
  cmd/lotus-seal-worker/main.go
  cmd/lotus-seal-worker/tasks.go
  documentation/en/cli-lotus-worker.md
  documentation/en/default-lotus-miner-config.toml
  extern/sector-storage/manager.go
  node/config/def.go
Labels: release/backport

#8088 fix:paychan:deflake integration test
  itests/kit/blockminer.go
  itests/paych_api_test.go
Labels: impact/test-flakiness

#8099 don't track peer ids in rcmgr metrics
  node/modules/lp2p/rcmgr.go
Labels: release/backport

#8108 feat: tweak v15 migration params
  chain/consensus/filcns/upgrades.go
Labels: release/backport

#8121 sealer: fix error message
  extern/storage-sealing/checks.go
Labels: release/backport

#8130 feat: Snapdeals support in `storage find` CLI
  cmd/lotus-miner/info_all.go
  cmd/lotus-miner/storage.go
Labels: release/backport

#8169 deps: update go-libp2p to v0.18.0-rc5
  go.mod
  go.sum
Labels: release/backport

#8177 fix:proving:post check sector handles snap deals replica faults
  api/api_storage.go
  api/proxy_gen.go
  api/version.go
  build/openrpc/miner.json.gz
  cmd/lotus-miner/proving.go
  documentation/en/api-v0-methods-miner.md
  extern/sector-storage/faults.go
  extern/sector-storage/mock/mock.go
  node/impl/storminer.go
  storage/wdpost_run.go
  storage/wdpost_run_test.go
Labels: P1, release/backport

#8181 fix:sealing:really-do-it flag for abort upgrade
  cmd/lotus-miner/sectors.go
Labels: release/backport

#7928 misc: wallet: wallet tests with annotations for system test matrix
  chain/wallet/multi_test.go
  chain/wallet/wallet_test.go
Labels: Bloxico - testing improvements (milestone 3)
