Repository filecoin-project/lotus, pull requests merged in 2022-03, with the labels that each got.

#7883 feat: paychmgr: Support paych funding (a.k.a. fast paid retrieval)
  api/api_full.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  api/v0api/v1_wrapper.go
  build/openrpc/full.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cli/paych.go
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  documentation/en/cli-lotus.md
  documentation/en/default-lotus-config.toml
  go.mod
  go.sum
  itests/paych_api_test.go
  itests/paych_cli_test.go
  markets/retrievaladapter/client.go
  node/builder_chain.go
  node/config/doc_gen.go
  node/config/types.go
  node/impl/paych/paych.go
  node/modules/client.go
  paychmgr/cbor_gen.go
  paychmgr/manager.go
  paychmgr/paych.go
  paychmgr/paych_test.go
  paychmgr/paychget_test.go
  paychmgr/paychvoucherfunds_test.go
  paychmgr/settle_test.go
  paychmgr/simple.go
  paychmgr/store.go
  testplans/lotus-soup/deals_e2e.go
  testplans/lotus-soup/go.mod
  testplans/lotus-soup/go.sum
  testplans/lotus-soup/paych/stress.go
Labels: kind/enhancement, area/payment-channel

#8229 fix:sealing:Handle finalize replica update failures in fsm
  cmd/lotus-miner/info.go
  extern/storage-sealing/fsm.go
  extern/storage-sealing/sector_state.go
Labels: release/backport

#8273 feat(deps): update to graphsync v0.13.0 with 2.0 protocol
  api/docgen/docgen.go
  api/types.go
  build/openrpc/miner.json.gz
  documentation/en/api-v0-methods-miner.md
  go.mod
  go.sum
  node/impl/storminer.go
Labels: P1

#8330 feat: sealing: Sector upgrade queue
  cmd/lotus-miner/info.go
  cmd/lotus-miner/sectors.go
  documentation/en/default-lotus-miner-config.toml
  extern/storage-sealing/fsm.go
  extern/storage-sealing/fsm_events.go
  extern/storage-sealing/input.go
  extern/storage-sealing/mocks/api.go
  extern/storage-sealing/sealiface/config.go
  extern/storage-sealing/sealing.go
  extern/storage-sealing/sector_state.go
  extern/storage-sealing/states_failed.go
  extern/storage-sealing/states_proving.go
  extern/storage-sealing/states_replica_update.go
  extern/storage-sealing/states_sealing.go
  extern/storage-sealing/upgrade_queue.go
  itests/ccupgrade_test.go
  itests/kit/log.go
  node/config/doc_gen.go
  node/config/types.go
  node/modules/storageminer.go
  storage/adapter_storage_miner.go
Labels: release/backport

#8345 fix: itests: Don't hang on exit in MineBlocksMustPost
  itests/kit/blockminer.go
Labels: impact/test-flakiness

#8355 deps: update go-libp2p to v0.18 release
  go.mod
  go.sum
Labels: release/backport

#8420 fix: sealing: Fix PR1 worker selection
  extern/sector-storage/manager.go
Labels: release/backport
