Repository filecoin-project/lotus, pull requests merged in 2022-08, with the labels that each got.

#9096 _ci_: Use goreleaser to build macos universal binaries (including M1 macs)
  .circleci/config.yml
  .circleci/template.yml
  .gitignore
  .goreleaser.yaml
  scripts/generate-checksums.sh
  scripts/publish-checksums.sh
Labels: release/backport

#9119 _ci_: Publish to both `lotus` and `lotus-filecoin` for snap
  .circleci/config.yml
  .circleci/template.yml
Labels: release/backport

#9120 _ci_: Switches goreleaser notes back to default (keep-existing)
  .goreleaser.yaml
Labels: release/backport

#9122 _ci_ : Change default shell options for snapcraft publish
  .circleci/config.yml
  .circleci/template.yml
Labels: release/backport

#9133 _ci_: Run snap builds for lotus and lotus-filecoin in parallel
  .circleci/config.yml
  .circleci/template.yml
Labels: release/backport

#9153 fix: worker: Close all storage paths on worker shutdown
  api/api_worker.go
  api/proxy_gen.go
  build/openrpc/full.json.gz
  build/openrpc/gateway.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cmd/lotus-worker/main.go
  cmd/lotus-worker/sealworker/rpc.go
  documentation/en/api-v0-methods-worker.md
Labels: release/backport

#9170 Update xcode version for macos builds
  .circleci/config.yml
  .circleci/template.yml
Labels: release/backport

#9183 feat: sealing: Use bitfields to manage sector numbers
  .circleci/config.yml
  api/api_full.go
  api/api_storage.go
  api/docgen/docgen.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  build/openrpc/full.json.gz
  build/openrpc/gateway.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  cmd/lotus-miner/init.go
  cmd/lotus-miner/sectors.go
  documentation/en/api-v0-methods-miner.md
  documentation/en/api-v1-unstable-methods.md
  documentation/en/cli-lotus-miner.md
  itests/kit/ensemble.go
  itests/sector_numassign_test.go
  lib/strle/human.go
  lib/strle/human_test.go
  node/builder_miner.go
  node/impl/full/state.go
  node/impl/storminer.go
  node/modules/storageminer.go
  storage/pipeline/input.go
  storage/pipeline/mocks/api.go
  storage/pipeline/numassign.go
  storage/pipeline/sealing.go
  storage/pipeline/types.go
  testplans/lotus-soup/testkit/role_miner.go
Labels: kind/enhancement, area/sealing

#9232 cli: Don't panic with no providers in client retrieve
  cli/client_retr.go
Labels: impact/test-flakiness
