Repository filecoin-project/lotus, pull requests merged in 2023-01, with the labels that each got.

#9481 IPC: Abstract common consensus functions and consensus interface
  api/api_full.go
  api/docgen/docgen.go
  api/v0api/full.go
  chain/consensus/common.go
  chain/consensus/compute_state.go
  chain/consensus/filcns/filecoin.go
  chain/consensus/filcns/mine.go
  chain/consensus/iface.go
  chain/gen/gen.go
  chain/gen/genesis/genesis.go
  chain/gen/genesis/miners.go
  chain/stmgr/forks_test.go
  chain/store/store_test.go
  chain/sub/incoming.go
  cli/chain.go
  cli/multisig.go
  cli/services.go
  cli/state.go
  cmd/lotus-bench/import.go
  cmd/lotus-shed/balances.go
  cmd/lotus-shed/gas-estimation.go
  cmd/lotus-shed/invariants.go
  cmd/lotus-shed/migrations.go
  cmd/lotus-shed/msg.go
  cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go
  cmd/lotus-sim/simulation/node.go
  cmd/lotus-sim/simulation/simulation.go
  cmd/lotus-wallet/interactive.go
  cmd/lotus/daemon.go
  cmd/tvx/extract_many.go
  conformance/driver.go
  lib/sigs/secp/init.go
  node/builder_chain.go
Labels: IPC

#10071 add integration test to catch tipset CID flakiness.
  .circleci/config.yml
  itests/deals_padding_test.go
  itests/deals_power_test.go
  itests/eth_block_hash_test.go
  itests/eth_deploy_test.go
  itests/kit/node_full.go
Labels: v1.20.0-pre-rc.5

#10052 itests: Add tests for EthGetLogs filter combinations
  chain/events/filter/event.go
  chain/events/filter/index.go
  chain/types/ethtypes/eth_types.go
  itests/contracts/EventMatrix.hex
  itests/contracts/EventMatrix.sol
  itests/contracts/events.asm
  itests/eth_filter_test.go
  itests/kit/evm.go
  itests/kit/log.go
  node/impl/full/eth.go
Labels: FEVM
