Repository filecoin-project/lotus, pull requests merged in 2024-12, with the labels that each got.

#12746 chore(release): cherry-pick v1.31.0 changelog back to master
  CHANGELOG.md
Labels: skip/changelog

#12753 chore: upgrade to go-f3 `v0.7.3`
  api/docgen/docgen.go
  build/openrpc/full.json
  documentation/en/api-v1-unstable-methods.md
  go.mod
  go.sum
Labels: release/backport, skip/changelog

#12751 chore(deps): update actors bundle to v16.0.0-dev
  build/actors/pack.sh
  build/actors/v16.tar.zst
  build/builtin_actors_gen.go
Labels: skip/changelog

#12749 ci: automate release issue creation from v1.32.0 learnings
  cmd/release/main.go
  documentation/misc/RELEASE_ISSUE_TEMPLATE.md
  go.mod
  go.sum
Labels: skip/changelog

#12764 fix: f3 gen power command being non-deterministic
  cmd/lotus-shed/f3.go
Labels: skip/changelog

#12741 ci: automate release issue creation
  .github/workflows/create-release-issue.yml
  cmd/release/README.md
  cmd/release/main.go
  documentation/misc/RELEASE_ISSUE_TEMPLATE.md
  go.mod
  go.sum
Labels: skip/changelog

#12759 chore(test): unflake TestTraceFilter
  itests/eth_transactions_test.go
Labels: skip/changelog

#12763 fix(sync): mark blocks which diverge from checkpoint as bad
  chain/sync.go
  chain/sync_test.go
Labels: skip/changelog

#12768 chore: remove IPNI advertisement relay over pubsub via Lotus node
  CHANGELOG.md
  build/params_shared_funcs.go
  chain/sub/incoming.go
  chain/sub/incoming_test.go
  go.mod
  go.sum
  node/builder.go
  node/builder_chain.go
  node/modules/lp2p/pubsub.go
  node/modules/services.go
Labels: release/backport

#12770 feat: optimize ForEachClaim to return only eligible claims
  chain/actors/builtin/power/actor.go.template
  chain/actors/builtin/power/power.go
  chain/actors/builtin/power/state.go.template
  chain/actors/builtin/power/v0.go
  chain/actors/builtin/power/v10.go
  chain/actors/builtin/power/v11.go
  chain/actors/builtin/power/v12.go
  chain/actors/builtin/power/v13.go
  chain/actors/builtin/power/v14.go
  chain/actors/builtin/power/v15.go
  chain/actors/builtin/power/v16.go
  chain/actors/builtin/power/v2.go
  chain/actors/builtin/power/v3.go
  chain/actors/builtin/power/v4.go
  chain/actors/builtin/power/v5.go
  chain/actors/builtin/power/v6.go
  chain/actors/builtin/power/v7.go
  chain/actors/builtin/power/v8.go
  chain/actors/builtin/power/v9.go
  chain/lf3/ec.go
  cmd/lotus-shed/sectors.go
  cmd/lotus-sim/simulation/stages/precommit_stage.go
  cmd/lotus-sim/simulation/stages/provecommit_stage.go
  cmd/lotus-sim/simulation/stages/windowpost_stage.go
  go.mod
  go.sum
  tools/stats/points/collect.go
Labels: skip/changelog

#12773 docs: fix lowercase initials and typos
  cli/chain.go
  cli/multisig.go
Labels: skip/changelog

#12775 chore: update to golang crypto `0.31.0`
  go.mod
  go.sum
Labels: release/backport, skip/changelog

#12779 chore: unset nv25 upgrade height on Calibnet
  build/buildconstants/params_calibnet.go
Labels: release/backport, skip/changelog

#12784 fix: bad error message capitalisation
  cli/chain.go
  cli/spcli/actor.go
  cmd/lotus-shed/actor.go
  cmd/lotus-shed/keyinfo.go
  cmd/lotus-shed/math.go
  tools/stats/influx/influx.go
  tools/stats/ipldstore/ipldstore.go
Labels: skip/changelog

#12782 fix(shed): lotus-shed f3 certs command -n arg not -N
  cmd/lotus-shed/f3.go
Labels: skip/changelog

#12781 fix(f3): test API during inactive-F3 modes and make consistent and safe
  chain/lf3/f3.go
  itests/f3_test.go
  node/impl/full/f3.go
Labels: skip/changelog

#12783 fix: make DealStatesEqual work properly
  chain/actors/builtin/market/actor.go.template
  chain/actors/builtin/market/market.go
Labels: skip/changelog

#12774 feat(ci): go list check versions available for untagged dependencies
  .github/workflows/dependency-check.yml
  go.mod
Labels: skip/changelog

#12740 feat: enforce dependency on released versions of packages
  .github/workflows/dependency-check.yml
  CONTRIBUTING.md
  go.mod
Labels: skip/changelog

#12801 chore: use time.Since instead of time.Now().Sub
  chain/sub/incoming.go
  cli/info.go
  cmd/lotus-miner/info.go
  cmd/lotus-miner/proving.go
  cmd/lotus-miner/sealing.go
  cmd/lotus-miner/storage.go
  miner/warmup.go
  storage/paths/fetch.go
  storage/paths/local.go
  storage/paths/localstorage_cached.go
  storage/sealer/fsutil/filesize_unix.go
  storage/wdpost/wdpost_run.go
  tools/stats/points/collect.go
Labels: skip/changelog
