Repository filecoin-project/lotus, pull requests merged in 2024-03, with the labels that each got.

#11671 feat: CLI: add expiration to claim list
  cli/filplus.go
Labels: release/backport

#11712 Enable event storage config for Actor events as well
  node/builder_chain.go
Labels: release/backport

#11710 sealing pipeline: Fix failing ProveCommit3 aggregate
  .circleci/config.yml
  .circleci/template.yml
  itests/kit/ensemble_opts.go
  itests/sector_pledge_test.go
  storage/pipeline/commit_batch.go
Labels: release/backport

#11704 fix: commit batch: Always go through commit batcher
  storage/pipeline/commit_batch.go
  storage/pipeline/fsm.go
  storage/pipeline/fsm_test.go
  storage/pipeline/sector_state.go
  storage/pipeline/states_sealing.go
Labels: release/backport

#11708 sealing pipeline: Fix panic on padding pieces in WaitDeals
  storage/pipeline/fsm.go
  storage/pipeline/input.go
  storage/pipeline/types.go
Labels: release/backport

#11663 fix: stmgr: do not use cached migration results if absent from the blockstore
  chain/stmgr/forks.go
  chain/stmgr/stmgr.go
Labels: release/backport

#11717 chore: events: Prevent DDL re-execution during event index schema migrations
  chain/events/filter/index.go
Labels: area/events

#11725 fix(events,gateway): check that filter.FromHeight isn't too far back for gateway calls
  gateway/proxy_fil.go
Labels: release/backport

#11724 feat: add ChainGetEvents to the gateway API
  api/api_gateway.go
  api/proxy_gen.go
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  gateway/node.go
  gateway/proxy_fil.go
Labels: release/backport

#11742 fix(events): don't log.Warn for EVM events with non-Raw codec
  node/impl/full/eth_events.go
Labels: release/backport

#11739 chore: deps: update boxo/libp2p/graphsync
  CHANGELOG.md
  blockstore/ipfs.go
  go.mod
  go.sum
Labels: release/backport

#11601 feat: shed: Add v13 migration to migrate-state
  cmd/lotus-shed/adl.go
  cmd/lotus-shed/diff.go
  cmd/lotus-shed/main.go
  cmd/lotus-shed/migrations.go
  go.mod
Labels: P1
