Repository filecoin-project/lotus, pull requests merged in 2024-08, with the labels that each got.

#12333 chore: fix some comments
  chain/market/fundmanager.go
  cli/evm.go
  cmd/lotus-shed/migrations.go
  documentation/en/cli-lotus.md
  storage/pipeline/fsm_test.go
  storage/pipeline/input.go
  storage/pipeline/upgrade_queue.go
Labels: skip/changelog

#12336 chore: deps: update hamt to latest
  go.mod
  go.sum
Labels: skip/changelog

#12349 chore: docs: Update step in skeleton guide
  documentation/misc/Building_a_network_skeleton.md
Labels: skip/changelog

#12361 docs: seed CONTRIBUTING.md with pr title and changelog expectations
  .github/pull_request_template.md
  .github/workflows/changelog.yml
  .github/workflows/pr-title-check.yml
  CONTRIBUTING.md
Labels: skip/changelog

#11581 chore: ffi: copy verifier iface, mock & ffi out of storage
  chain/consensus/filcns/filecoin.go
  chain/gen/gen.go
  chain/proofs/ffi/verifier_cgo.go
  chain/proofs/mock/mock.go
  chain/proofs/proofs.go
  chain/proofs/proofs_test.go
  chain/proofs/verifier.go
  chain/stmgr/actors.go
  chain/vm/syscalls.go
  cmd/lotus-bench/caching_verifier.go
  cmd/lotus-bench/import.go
  cmd/lotus-bench/main.go
  cmd/lotus-seed/genesis.go
  cmd/lotus-shed/balances.go
  cmd/lotus-shed/gas-estimation.go
  cmd/lotus-shed/invariants.go
  cmd/lotus-shed/migrations.go
  cmd/lotus-shed/state-stats.go
  cmd/lotus-sim/simulation/mock/mock.go
  cmd/lotus/daemon.go
  conformance/driver.go
  itests/kit/ensemble.go
  node/builder_chain.go
  node/impl/full/state.go
Labels: skip/changelog

#12358 fix: chain: use instance-local verifier to VerifyWinningPoSt
  chain/consensus/filcns/filecoin.go
Labels: skip/changelog

#12366 docs: expand `CONTRIBUTING.md` and update `README.md`
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: skip/changelog

#12367 fix(ci): support checking forks in PR-title check workflow
  .github/workflows/pr-title-check.yml
Labels: skip/changelog

#12356 docs: release template: update based on 1.28 learnings
  documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Labels: skip/changelog

#12370 ci: improve stalebot behavior/language
  .github/workflows/stale.yml
Labels: skip/changelog

#12380 chore: bump `MinerBuildVersion` in master to v1.28.3-dev
  build/version.go
  documentation/en/cli-lotus-miner.md
  documentation/en/cli-lotus-worker.md
Labels: skip/changelog

#12375 chore: deprecate "releases" branch by providing clear messaging
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/test.yml
  Makefile
  README.md
Labels: skip/changelog

#12382 feat(f3): update from v0.0.7 to v0.1.0
  CHANGELOG.md
  chain/lf3/manifest.go
  go.mod
  go.sum
Labels: release/backport

#12390 feat: f3: update go-f3 to 0.2.0
  CHANGELOG.md
  go.mod
  go.sum
Labels: release/backport

#12396 docs: update references to releases branch
  README.md
Labels: skip/changelog

#12400 chore: post release steps for #12379 (v1.28.2 miner and node patch release)
  CHANGELOG.md
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12406 [skip changelog] fix: error check
  storage/pipeline/pledge.go
Labels: team/curio

#12409 build: update Lotus Node version to v1.29.1-dev in master
  CHANGELOG.md
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12410 build: release Lotus node v1.29.0-rc1
  CHANGELOG.md
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus.md
Labels: skip/changelog
