Repository filecoin-project/lotus, pull requests merged in 2024-02, with the labels that each got.

#11637 chore: Update epoch heights for nv22
  build/params_calibnet.go
  build/params_mainnet.go
Labels: P1

#11636 new: add forest bootstrap nodes
  build/bootstrap/calibnet.pi
  build/bootstrap/mainnet.pi
Labels: P1, release/backport

#11609 feat: api: improve the correctness of Eth's trace_block
  CHANGELOG.md
  api/api_full.go
  build/openrpc/full.json
  build/openrpc/full.json.gz
  build/openrpc/gateway.json
  build/openrpc/gateway.json.gz
  chain/actors/builtin/evm/actor.go.template
  chain/actors/builtin/evm/evm.go
  chain/types/ethtypes/eth_types.go
  documentation/en/api-v1-unstable-methods.md
  node/impl/full/eth.go
  node/impl/full/eth_test.go
  node/impl/full/eth_trace.go
  node/impl/full/eth_utils.go
Labels: P1, release/backport

#11491 Remove PL operated bootstrap nodes from mainnet.pi
  build/bootstrap/mainnet.pi
Labels: P1, release/backport

#11631 feat: api: new verified registry methods to get all allocations and claims
  CHANGELOG.md
  api/api_full.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  api/v0api/full.go
  api/v0api/proxy_gen.go
  api/v0api/v0mocks/mock_full.go
  build/openrpc/full.json.gz
  build/openrpc/gateway.json.gz
  build/openrpc/miner.json.gz
  build/openrpc/worker.json.gz
  chain/actors/builtin/verifreg/actor.go.template
  chain/actors/builtin/verifreg/state.go.template
  chain/actors/builtin/verifreg/v0.go
  chain/actors/builtin/verifreg/v10.go
  chain/actors/builtin/verifreg/v11.go
  chain/actors/builtin/verifreg/v12.go
  chain/actors/builtin/verifreg/v13.go
  chain/actors/builtin/verifreg/v2.go
  chain/actors/builtin/verifreg/v3.go
  chain/actors/builtin/verifreg/v4.go
  chain/actors/builtin/verifreg/v5.go
  chain/actors/builtin/verifreg/v6.go
  chain/actors/builtin/verifreg/v7.go
  chain/actors/builtin/verifreg/v8.go
  chain/actors/builtin/verifreg/v9.go
  chain/actors/builtin/verifreg/verifreg.go
  cli/filplus.go
  cli/util.go
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  documentation/en/cli-lotus.md
  itests/verifreg_test.go
  node/impl/full/state.go
Labels: P2

#11632 feat: drand quicknet: allow scheduling drand quicknet upgrade before nv22 on 2k devnet
  build/drand.go
  build/params_2k.go
  chain/beacon/beacon.go
  chain/beacon/drand/drand.go
  chain/beacon/drand/drand_test.go
  chain/beacon/mock.go
  node/modules/dtypes/beacon.go
Labels: P2
