Repository filecoin-project/lotus, pull requests merged in 2024-07, with the labels that each got.

#12135 feat: api: sanity check the "to" address of outgoing messages
  itests/mempool_test.go
  node/impl/full/mpool.go
  node/impl/full/mpool_test.go
Labels: release/backport

#12175 fix: build: Ensure Quicknet is used when spinning up 2k/butterfly networks
  build/params_2k.go
  build/params_butterfly.go
  build/params_interop.go
Labels: release/backport

#12177 fix: rpc: missing re-assignment of baseFee in EthFeeHistory
  node/impl/full/eth.go
Labels: release/backport

#12181 feat: calib: enable f3 by default
  build/params_calibnet.go
Labels: release/backport

#12176 feat:ec:f3: add env var to disable F3
  build/params_2k.go
  build/params_butterfly.go
  build/params_calibnet.go
  build/params_interop.go
  build/params_mainnet.go
  build/params_shared_funcs.go
  node/builder_chain.go
  node/builder_miner.go
  node/modules/lp2p/pubsub.go
Labels: release/backport

#12173 feat:ec: integrate F3 dynamic manifest
  build/params_2k.go
  build/params_butterfly.go
  build/params_calibnet.go
  build/params_interop.go
  build/params_mainnet.go
  chain/lf3/ec.go
  chain/lf3/f3.go
  chain/lf3/manifest.go
  go.mod
  go.sum
  node/builder_chain.go
  node/modules/lp2p/pubsub.go
Labels: release/backport

#12191 ci: add changelog check workflow
  .github/pull_request_template.md
  .github/workflows/changelog.yml
Labels: skip-changelog

#12200 [skip changelog]: fix: flaky eth_legacy_tx_test: wait for async msg indexing
  itests/kit/evm.go
Labels: skip-changelog

#12180 feat: niporep: multi-sector onboarding through UnmanagedMiner
  itests/kit/ensemble.go
  itests/kit/node_unmanaged.go
  itests/manual_onboarding_test.go
  itests/niporep_manual_test.go
Labels: skip/changelog

#12201 chore: docs: Update label to `skip/changelog` in the PR-template
  .github/pull_request_template.md
Labels: skip/changelog

#12207 fix: ETH getLogs: fix slowness at head and ignore null blocks
  chain/events/filter/index.go
  chain/events/filter/index_test.go
  node/impl/full/eth.go
Labels: release/backport, skip/changelog

#12196 feat: F3: Update go-f3, change the style of participation call
  api/api_full.go
  api/docgen/docgen.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  chain/lf3/ec.go
  chain/lf3/f3.go
  chain/lf3/leasemanager.go
  chain/lf3/leasemanager_test.go
  chain/lf3/manifest.go
  chain/lf3/signer.go
  documentation/en/api-v1-unstable-methods.md
  go.mod
  go.sum
  node/impl/full/f3.go
  node/modules/storageminer.go
Labels: release/backport, skip/changelog

#12220 fix: test: use parents instead of height-1 to calculate sector activation epoch
  itests/kit/node_unmanaged.go
Labels: skip/changelog

#12216 chore: f3: Upgrade go mod F3 dependency to v0.0.3 tagged release
  CHANGELOG.md
  chain/lf3/f3.go
  go.mod
  go.sum
Labels: release/backport

#12224 fix: bug: Reduce log level in F3 message sending to Debug
  chain/lf3/f3.go
Labels: release/backport, skip/changelog

#12219 fix: eth: make tx hash immediately available in lookup db after submission
  node/impl/full/eth.go
Labels: skip/changelog

#12230 chore: deps: upgrade to go-state-types@v0.14.0-rc6
  go.mod
  go.sum
Labels: release/backport, skip/changelog

#12098 feat: sqlite: extract common init and migration utilities
  chain/ethhashlookup/eth_transaction_hash_lookup.go
  chain/events/filter/index.go
  chain/events/filter/index_migrations.go
  chain/index/msgindex.go
  chain/index/msgindex_test.go
  cmd/lotus/daemon.go
  itests/msgindex_test.go
  lib/sqlite/sqlite.go
  lib/sqlite/sqlite_test.go
  node/modules/actorevent.go
  node/modules/ethmodule.go
  node/modules/msgindex.go
Labels: skip/changelog

#12229 fix: build break for Docker test environments
  build/buildconstants/params_2k.go
  build/buildconstants/params_butterfly.go
  build/buildconstants/params_calibnet.go
  build/buildconstants/params_debug.go
  build/buildconstants/params_interop.go
  build/buildconstants/params_mainnet.go
  build/buildconstants/params_shared_vals.go
  build/params_shared_vals.go
  build/params_testground_vals.go
Labels: skip/changelog

#12235 fix: ethhashlookup: clean-up query management and lifecycle
  chain/ethhashlookup/eth_transaction_hash_lookup.go
Labels: skip/changelog

#12240 chore: libp2p: update to v0.35.3
  go.mod
  go.sum
Labels: release/backport, skip/changelog

#12245 [skip changelog] chore: types: buildconstants split post-cleanup
  build/buildconstants/params_mainnet.go
  build/buildconstants/params_shared_vals.go
  build/buildconstants/params_testground.go
  build/buildconstants/shared_funcs.go
  build/builtin_actors_gen.go
  build/params_shared_funcs.go
  build/params_shared_vals.go
  gen/bundle/bundle.go
  itests/eth_hash_lookup_test.go
Labels: release/backport

#12243 fix: flaky wdPost dispute itest
  itests/wdpost_dispute_test.go
Labels: skip/changelog

#12247 misc: add waffle to match w/ forest
  chain/consensus/filcns/FVMLiftoff.txt
  chain/consensus/filcns/UpgradeSplash.txt
  chain/consensus/filcns/upgrades.go
Labels: skip/changelog

#12257 chore: all: fix comment
  blockstore/badger/blockstore.go
  chain/beacon/mock.go
  cli/util/api.go
  cmd/lotus-sim/simulation/node.go
  node/builder.go
Labels: skip/changelog

#12265 chore: libp2p: update to v0.35.4
  go.mod
  go.sum
Labels: release/backport, skip/changelog

#12252 [skip changelog] chore: config: yet more lp2p removal from miner
  documentation/en/default-lotus-miner-config.toml
  node/builder.go
  node/builder_chain.go
  node/builder_miner.go
  node/config/def.go
  node/config/doc_gen.go
  node/config/types.go
Labels: release/backport

#12253 fix(store): correctly break weight ties based on smaller ticket
  chain/store/store.go
  chain/store/weight_test.go
Labels: release/backport, skip/changelog

#12268 fix: lotus-miner: batch expired sector removal in lotus-miner
  cmd/lotus-miner/sectors.go
Labels: skip/changelog

#12275 fix: exchange bug
  chain/exchange/client.go
  chain/exchange/protocol.go
  node/hello/hello.go
Labels: release/backport, skip/changelog

#12267 test: events: test sqlite indexes used in query plan of all selects and updates
  chain/events/filter/index.go
  chain/events/filter/index_test.go
Labels: skip/changelog

#12285 metrics: f3: Set up otel metrics reporting to prometheus
  CHANGELOG.md
  chain/lf3/f3.go
  go.mod
  go.sum
Labels: release/backport

#12280 Docs: Update Building_a_network_skeleton.md
  documentation/misc/Building_a_network_skeleton.md
Labels: skip/changelog

#12256 chore: ui: add a terminal check
  chain/consensus/filcns/upgrades.go
Labels: skip/changelog

#12251 fix: lotus-miner: remove provecommit1 method
  CHANGELOG.md
  storage/pipeline/commit_batch.go
  storage/pipeline/states_replica_update.go
  storage/pipeline/states_sealing.go
Labels: release/backport

#12096 feat: ci: automate the new release process
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  cmd/release/README.md
  cmd/release/main.go
  documentation/misc/RELEASE_ISSUE_TEMPLATE.md
  go.mod
  scripts/publish-checksums.sh
  scripts/version-check.sh
Labels: skip/changelog

#12309 fix:cli:Add delegated to cli docs
  cli/wallet.go
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12314 fix: events: don't initialise events helpers when not needed
  node/builder_chain.go
Labels: area/events, skip/changelog

#12321 fix: docs: address typo
  documentation/en/architecture/architecture.md
Labels: skip/changelog

#12318 fix: events: remove filter if we fail to add it to the FilterStore
  node/impl/full/eth.go
Labels: skip/changelog

#12328 fix: send cli: only override method if recipient is a "0x" address
  cli/send.go
Labels: skip/changelog
