Repository filecoin-project/lotus, pull requests merged in 2024-10, with the labels that each got.

#12538 chore(deps): upgrade go-ipld-cbor
  go.mod
  go.sum
Labels: skip/changelog

#12537 chore(eth): add some debugging to TestTraceFilter
  itests/eth_transactions_test.go
Labels: skip/changelog

#12539 fix: eth_getBlockReceipts should work similarly as geth
  chain/types/ethtypes/eth_types.go
  chain/types/ethtypes/eth_types_test.go
  itests/fevm_test.go
Labels: skip/changelog

#12542 fix: daemon: ensure imports are unaffected by remote-EOF
  cmd/lotus/daemon.go
  lib/httpreader/resumable.go
Labels: skip/changelog

#12552 feat(f3): prepare for f3 bootstrap
  chain/lf3/config.go
  chain/lf3/manifest.go
  go.mod
  go.sum
  itests/f3_test.go
  itests/kit/node_opts.go
  node/builder_chain.go
  node/modules/lp2p/pubsub.go
Labels: skip/changelog

#12564 build: release Lotus node and miner v1.30.0-rc1
  CHANGELOG.md
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus-miner.md
  documentation/en/cli-lotus-worker.md
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12572 fix: update actor code ID in lotus-shed invariant check
  cmd/lotus-shed/migrations.go
Labels: release/backport, skip/changelog

#12574 fix: set address current network for non-mainnet since default is changed
  build/buildconstants/params_2k.go
  build/buildconstants/params_2k_test.go
  build/buildconstants/params_butterfly_test.go
  build/buildconstants/params_calibnet_test.go
  build/buildconstants/params_interop_test.go
  build/buildconstants/params_mainnet_test.go
  build/buildconstants/params_testground.go
  build/buildconstants/params_testground_test.go
Labels: skip/changelog

#12573 chore: set Calibration upgrade epoch for nv24
  build/buildconstants/params_calibnet.go
Labels: release/backport, skip/changelog

#12575 fix(f3): fix hot loop in F3 participation
  CHANGELOG.md
  itests/f3_test.go
  node/modules/storageminer.go
Labels: release/backport

#12576 fix(f3): improve log messages
  node/modules/storageminer.go
Labels: skip/changelog

#12578 fix(f3): log the correct number of instances remaining
  api/api_full.go
  chain/lf3/participation_lease.go
  node/modules/storageminer.go
Labels: skip/changelog

#12582 fix(f3): use the correct context in tests
  itests/f3_test.go
Labels: skip/changelog

#12581 feat(f3): log when gaining/losing participation leases
  chain/lf3/participation_lease.go
Labels: skip/changelog

#12562 build: update Node and Miner version to v1.30.1-dev in master
  CHANGELOG.md
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus-miner.md
  documentation/en/cli-lotus-worker.md
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12579 fix(f3): handle a case where we might receive no manifest
  node/modules/storageminer.go
Labels: skip/changelog

#12580 feat(f3): remove lease-check interval constants
  node/modules/storageminer.go
Labels: skip/changelog

#12577 fix(f3): send the last gpbft message for each new participant
  chain/lf3/f3.go
  chain/lf3/participation_lease.go
Labels: skip/changelog

#12588 fix: bug in exclude reverted logic for eth_getLogs
  chain/events/filter/event.go
Labels: skip/changelog

#12590 fix: fix address network override via env var
  build/buildconstants/params_mainnet.go
Labels: skip/changelog

#12589 feat(f3): refactor the F3 participation module for easier testing
  chain/lf3/participation.go
  itests/f3_test.go
  node/modules/storageminer.go
Labels: skip/changelog

#12592 fix(f3): don't return an error on stop if our context was canceled
  chain/lf3/participation.go
Labels: skip/changelog

#12556 test: validate MCOPY opcode for FIP-0094
  itests/contracts/mcopy/MCOPYTest.hex
  itests/contracts/mcopy/MCOPYTest.sol
  itests/fevm_test.go
  itests/kit/evm.go
Labels: release/backport, skip/changelog

#12596 chore: reduce verbosity of F3 logs during itest
  itests/kit/log.go
Labels: skip/changelog

#12595 fix(miner): fix new bug in StateMinerPreCommitDepositForPower calculation
  node/impl/full/state.go
Labels: release/backport, skip/changelog

#12602 chore: update triplewz/poseidon
  go.mod
  go.sum
  storage/sealer/commitment/commr.go
Labels: release/backport, skip/changelog

#12606 chore: backport #12602 to `release/v1.30.0` branch
  go.mod
  go.sum
  storage/sealer/commitment/commr.go
Labels: skip/changelog

#12605 chore(spcli): improve sectors extend sector skipping info logging
  cli/spcli/sectors.go
Labels: skip/changelog

#12609 feat(cli): lotus chain head --height to print epoch number
  CHANGELOG.md
  cli/chain.go
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12610 chore(events): remove unnecessary DisableRealTimeFilterAPI
  documentation/en/default-lotus-config.toml
  node/config/def.go
  node/config/doc_gen.go
  node/config/types.go
  node/modules/actorevent.go
Labels: skip/changelog

#12611 feat(cli): add --quiet to chainindex validate-backfill + cleanups
  cmd/lotus-shed/chain_index.go
Labels: skip/changelog

#12597 fix: determine F3 participants relative to current network name
  CHANGELOG.md
  chain/lf3/f3.go
  chain/lf3/participation_lease.go
  chain/lf3/participation_lease_test.go
  itests/f3_test.go
Labels: release/backport

#12612 chore(doc): "regular checks" section for chainindexer docs
  documentation/en/chain-indexer-overview-for-operators.md
Labels: skip/changelog

#12608 feat: implement F3 list participants API
  CHANGELOG.md
  api/api_full.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  chain/lf3/f3.go
  chain/lf3/participation_lease.go
  chain/lf3/participation_lease_test.go
  documentation/en/api-v1-unstable-methods.md
  itests/f3_test.go
  node/impl/full/f3.go
Labels: release/backport

#12613 chore(ci): allow ', ", ` characters to prefix commit description
  .github/workflows/pr-title-check.yml
Labels: skip/changelog

#12619 fix(chainindexer): backfilling should halt when chain state data is missing and not backfill parents
  chain/index/api.go
  cmd/lotus-shed/chain_index.go
Labels: skip/changelog

#12620 fix: handle negative value for `LOTUS_DISABLE_F3` env var gracefully
  build/params_shared_funcs.go
Labels: release/backport, skip/changelog

#12621 chore: remove redundant `F3Consensus` build parameter
  build/buildconstants/params_2k.go
  build/buildconstants/params_butterfly.go
  build/buildconstants/params_calibnet.go
  build/buildconstants/params_interop.go
  build/buildconstants/params_mainnet.go
  build/buildconstants/params_testground.go
Labels: release/backport, skip/changelog

#12600 docs: finishing chain-indexer-overview-for-operators.md
  CHANGELOG.md
  chain/index/chain-indexing-overview-for-rpc-providers.MD
  documentation/en/chain-indexer-overview-for-operators.md
Labels: skip/changelog

#12626 feat(f3): display the initial power table CID in the F3 manifest
  chain/lf3/f3.go
  cli/f3.go
  node/impl/full/f3.go
Labels: skip/changelog

#12628 fix(f3): correctly construct the manifest template
  cli/f3.go
Labels: skip/changelog

#12624 chore(logging): downgrade GasEstimateMessageGas info log to debug
  node/impl/full/gas.go
Labels: skip/changelog

#12632 feat(chainindex): compare events AMT root between Index and chain state for validation
  chain/index/api.go
  chain/index/api_test.go
  chain/index/ddls.go
  chain/index/ddls_test.go
  chain/index/indexer.go
Labels: skip/changelog

#12634 fix(f3): try again when we fail to fetch the manifest
  chain/lf3/participation.go
  chain/lf3/participation_test.go
Labels: release/backport, skip/changelog

#12638 feat(f3): lotus shed command to delete all f3 state
  cmd/lotus-shed/f3.go
  cmd/lotus-shed/main.go
Labels: skip/changelog

#12637 fix: fix F3 JSON RPC error pass through across API boundary
  api/api_errors.go
  itests/f3_test.go
Labels: release/backport, skip/changelog

#12627 feat: implement Lotus F3 CLI finality cert get and list
  CHANGELOG.md
  cli/f3.go
  cli/templates/f3_finality_cert.go.tmpl
  cli/templates/f3_manifest.go.tmpl
  documentation/en/cli-lotus.md
Labels: release/backport

#12640 fix(f3): poll the lease by repeatedly participating instead of checking progress
  CHANGELOG.md
  chain/lf3/participation.go
  chain/lf3/participation_lease.go
  chain/lf3/participation_lease_test.go
  chain/lf3/participation_test.go
Labels: release/backport

#12642 test(eth): fix execution/inclusion off-by-one
  itests/eth_conformance_test.go
Labels: skip/changelog

#12643 test(eth): fix bloom filter test flake
  itests/eth_filter_test.go
Labels: skip/changelog

#12641 Revert "feat: fix GetBlock for null rounds by returning nil (#12529)"
  CHANGELOG.md
  api/api_full.go
  api/api_gateway.go
  api/mocks/mock_full.go
  api/proxy_gen.go
  build/openrpc/full.json
  build/openrpc/gateway.json
  gateway/node.go
  gateway/proxy_eth.go
  itests/eth_api_test.go
  itests/eth_block_hash_test.go
  itests/eth_deploy_test.go
  itests/eth_transactions_test.go
  itests/fevm_test.go
  node/impl/full/dummy.go
  node/impl/full/eth.go
Labels: release/backport

#12645 fix(test): address minor lint issue
  itests/eth_filter_test.go
Labels: skip/changelog

#12648 feat(f3): change F3 HeadLookback to 4
  CHANGELOG.md
  chain/lf3/config.go
Labels: release/backport

#12649 chore(f3): set F3InitialPowerTableCID in calibnet
  build/buildconstants/params_calibnet.go
Labels: release/backport, skip/changelog

#12651 chore(f3): update go-f3 to v0.7.1
  CHANGELOG.md
  go.mod
  go.sum
Labels: release/backport

#12650 feat(chain): rework checkpoint logic to better handle finality
  chain/store/store.go
Labels: release/backport, skip/changelog

#12652 test(chain): test forking before/after finality
  chain/gen/gen.go
  chain/store/checkpoint_test.go
Labels: skip/changelog

#12657 fix(chainindex): retry transaction if database connection is lost
  chain/index/api.go
  chain/index/indexer.go
Labels: skip/changelog

#12656 chore(deps): update poseidon to the released version
  go.mod
  go.sum
Labels: skip/changelog

#12662 fix(miner): use the "from" address as the sender if it is set
  cmd/lotus-miner/init.go
Labels: skip/changelog

#12660 chore: set Mainnet upgrade epoch for NV24
  build/buildconstants/params_mainnet.go
Labels: release/backport, skip/changelog
