Repository filecoin-project/lotus, pull requests merged in 2024-11, with the labels that each got.

#12665 fix(api): make stick sessions actually work and make them non-racy
  CHANGELOG.md
  cli/util/api.go
  itests/merged_api_test.go
Labels: release/backport

#12667 fix(f3): when returning a partially used lease, trim its ValidityTerm
  chain/lf3/participation_lease.go
  chain/lf3/participation_lease_test.go
Labels: release/backport, skip/changelog

#12664 fix(f3): try to make f3 participation stick to a single node
  CHANGELOG.md
  chain/lf3/participation.go
Labels: release/backport

#12669 chore: conditionally change the limit of F3 certs listed via CLI
  cli/f3.go
  documentation/en/cli-lotus.md
Labels: release/backport, skip/changelog

#12672 feat(f3): allow to disable f3 passive testing
  build/params_shared_funcs.go
  chain/lf3/manifest.go
Labels: release/backport, skip/changelog

#12673 chore: change F3BootstrapEpoch to -1
  build/buildconstants/params_mainnet.go
Labels: release/backport, skip/changelog

#12676 chore: upgrade to go-f3 `v0.7.2`
  go.mod
  go.sum
Labels: release/backport, skip/changelog

#12678 build: release Lotus node|miner v1.30.0
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus-miner.md
  documentation/en/cli-lotus-worker.md
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12682 test: bogus cli change for testing purposes
  cmd/lotus/main.go
Labels: skip/changelog

#12668 feat(cli): shift chainindex validate-backfill command
  cli/clicommands/cmd.go
  cli/index.go
  cmd/lotus-shed/main.go
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12675 fix(eth): present revert "data" as plain bytes
  api/api_errors.go
  itests/fevm_test.go
  node/impl/full/eth.go
  node/impl/full/eth_utils.go
Labels: skip/changelog

#12683 chore(release): cherry-pick v1.30.0 changelog back to master
  CHANGELOG.md
Labels: skip/changelog

#12684 docs: update references for lotus-shed chainindex to lotus index
  cli/index.go
  documentation/en/chain-indexer-overview-for-operators.md
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12666 chore(deps): switch to the stdlib atomic package in snapshot code
  chain/store/snapshot.go
  go.mod
Labels: skip/changelog

#12694 fix: fix minor bugs in lotus shed datastore subcommand
  cmd/lotus-shed/datastore.go
Labels: skip/changelog

#12689 chore: fix struct name in comment
  storage/sealer/storiface/index.go
Labels: skip/changelog

#12700 chore: use DEBUG level log when F3 is not ready for participation
  chain/lf3/participation.go
Labels: skip/changelog

#12699 fix(test): unflake TestEthBlockNumberAliases
  itests/eth_api_test.go
Labels: skip/changelog

#12701 docs(indexer): more clarity for ChainIndexer configuration setup
  documentation/en/default-lotus-config.toml
  node/builder_chain.go
  node/config/doc_gen.go
  node/config/types.go
Labels: skip/changelog

#12708 docs: replace more references to lotus-shed with lotus in ChainIndexer docs
  documentation/en/chain-indexer-overview-for-operators.md
Labels: skip/changelog

#12703 feat(shed): lotus-shed sectors dump-sectors
  cmd/lotus-shed/sectors.go
  cmd/lotus-shed/state-stats.go
Labels: skip/changelog

#12712 chore(test): minor cleanup and debugging output for TestEthBlockHashesCorrect_MultiBlockTipset
  itests/eth_block_hash_test.go
Labels: skip/changelog

#12716 chore: fix function name
  api/api_storage.go
  build/openrpc/miner.json
  documentation/en/api-v0-methods-miner.md
Labels: skip/changelog

#12721 chore: backport #12603 to `release/v1.31.0` branch
  CHANGELOG.md
  chain/events/filter/event.go
  chain/events/filter/event_test.go
  node/modules/actorevent.go
Labels: skip/changelog

#12713 feat(shed): check command for FIP-0081 pledge calculation
  cmd/lotus-shed/balances.go
  itests/migration_test.go
Labels: skip/changelog

#12725 fix: skip checking the initial power table CID if undefined
  cli/f3.go
Labels: release/backport, skip/changelog

#12720 fix(miner): fix scary verified power miscalculation upon extension
  CHANGELOG.md
  cmd/lotus-miner/sectors.go
Labels: release/backport

#12729 chore: update go-libp2p to v0.37.2
  .github/actions/install-go/action.yml
  go.mod
  go.sum
Labels: skip/changelog

#12739 fix: use numerical formatting when printing F3 CLI error message
  cli/f3.go
Labels: release/backport, skip/changelog
