Repository filecoin-project/lotus, pull requests merged in 2025-07, with the labels that each got.

#13192 chore(docs): minor typo fixes
  blockstore/autobatch.go
  lib/backupds/cbor.go
  lib/sqlite/sqlite.go
  lib/ulimit/ulimit.go
  node/modules/core.go
Labels: skip/changelog

#11928 fix(cli): make lotus-miner sectors extend command resilient to higher gas
  CHANGELOG.md
  cli/spcli/sectors.go
  documentation/en/cli-lotus-miner.md
Labels: area/miner-maintenance

#12491 fix(miner): make UnpadReader be a correct Reader
  storage/sealer/fr32/readers.go
  storage/sealer/fr32/readers_test.go
Labels: skip/changelog

#13209 chore(docs): fix some typos in comment
  documentation/en/default-lotus-config.toml
  node/config/doc_gen.go
  node/config/load.go
  node/config/load_test.go
  node/config/types.go
  node/impl/full/state.go
Labels: skip/changelog

#13210 chore(docs): minor spelling mistakes in comments
  cmd/lotus-bench/rpc.go
  cmd/lotus-shed/state-stats.go
  cmd/tvx/state.go
Labels: skip/changelog

#13215 chore(docs): fix some minor issues in comments
  cmd/lotus-shed/f3.go
  cmd/lotus-shed/fevmanalytics.go
  cmd/lotus-shed/keyinfo.go
  paychmgr/simple.go
Labels: skip/changelog

#13218 ci: create add-issues-and-prs-to-fs-project-board.yml
  .github/workflows/add-issues-and-prs-to-fs-project-board.yml
Labels: team/fs-wg

#13235 chore: fix typos in docs
  blockstore/splitstore/README.md
  chain/actors/aerrors/wrap.go
Labels: skip/changelog

#13236 chore: bump go-f3 to v0.8.9
  go.mod
  go.sum
Labels: skip/changelog

#13237 chore: backport #13236 to the `release/v1.33.1` branch
  go.mod
  go.sum
Labels: skip/changelog
