Repository filecoin-project/lotus, pull requests merged in 2025-04, with the labels that each got.

#13000 chore: bump version to v1.32.2-dev
  build/openrpc/full.json
  build/openrpc/gateway.json
  build/openrpc/miner.json
  build/openrpc/worker.json
  build/version.go
  documentation/en/cli-lotus-miner.md
  documentation/en/cli-lotus-worker.md
  documentation/en/cli-lotus.md
Labels: skip/changelog

#12874 docs(release): v1.32.0 release template improvements
  LOTUS_RELEASE_FLOW.md
  cmd/release/main.go
  documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Labels: skip/changelog

#13002 refactor: use slices.Equal to simplify code
  chain/types/tipset.go
Labels: skip/changelog

#13007 chore: update new Mainnet nv25 date to 2025-04-14T23:00:00Z
  build/buildconstants/params_mainnet.go
Labels: skip/changelog

#13014 feat(shed): migrate-state tock-fix
  cmd/lotus-shed/migrations.go
Labels: skip/changelog

#12999 fix(eth): return nil for eth transactions not found
  CHANGELOG.md
  chain/stmgr/searchwait.go
  itests/eth_hash_lookup_test.go
  node/impl/eth/transaction.go
Labels: area/eth-api

#13020 docs(cli): add usage description for f3 powertable command
  cli/f3.go
  documentation/en/cli-lotus.md
Labels: skip/changelog

#13032 chore: fix generated docs on `master`
  build/openrpc/v2/full.json
  documentation/en/api-v2-unstable-methods.md
Labels: skip/changelog

#13033 chore: avoid test flakiness in v2 API tests caused by `WaitTillChain`
  itests/api_v2_test.go
Labels: skip/changelog

#13035 chore: mark generated openrpc and docs as generated
  .gitattributes
Labels: skip/changelog

#13037 feat(metrics): capture total gas metric from ApplyBlocks
  chain/consensus/compute_state.go
  metrics/metrics.go
Labels: skip/changelog

#12883 fix(eth): apply limit in EthGetBlockReceiptsLimited
  itests/fevm_test.go
  node/impl/eth/transaction.go
Labels: skip/changelog

#13042 fix(shed): account for new sectors that haven't been proven yet
  cmd/lotus-shed/miner-fees.go
Labels: skip/changelog

#13045 chore(docs): add more clarity to what StateMinerAvailableBalance is doing
  api/api_full.go
  build/openrpc/full.json
  documentation/en/api-v1-unstable-methods.md
Labels: skip/changelog

#13044 docs: remove consecutive duplicate words
  CHANGELOG.md
  documentation/en/sealing-procs.md
Labels: skip/changelog

#13031 chore: fix wrong comment
  itests/f3_test.go
Labels: skip/changelog

#13047 chore: fix function name in comment
  cmd/lotus-sim/simulation/stages/windowpost_stage.go
Labels: skip/changelog

#13050 chore: sysctl template, service burst limits
  scripts/98-udp-buf.conf
  scripts/lotus-daemon.service
Labels: skip/changelog

#13061 chore: reduce log level for F3 participation lease renewal
  chain/lf3/participation.go
Labels: skip/changelog

#13051 docs: add "safe" tag to V2 API documentation
  build/buildconstants/params_shared_vals.go
  documentation/en/api-experimental-user-facing-v2-docs/CLAUDE.md
  documentation/en/api-experimental-user-facing-v2-docs/api-v2-experimental.md
Labels: skip/changelog

#12939 feat: set up very expensive tests to run in CI
  .github/workflows/reusable-test.yml
  .github/workflows/very-expensive-test.yml
  cmd/ci/main.go
Labels: skip/changelog, need/very-expensive-tests

#13077 feat(f3): set initial power table for mainnet
  CHANGELOG.md
  build/buildconstants/params_mainnet.go
Labels: release/backport

#13068 docs: add ETH API information to V2 API documentation
  documentation/en/api-experimental-user-facing-v2-docs/CLAUDE.md
  documentation/en/api-experimental-user-facing-v2-docs/api-v2-experimental.md
Labels: skip/changelog
