Repository filecoin-project/lotus, pull requests merged in 2025-03, with the labels that each got.

#12929 feat(f3): add F3ParamsAddress to buildconstants, wire it in, specify Butterfly
  build/buildconstants/params_2k.go
  build/buildconstants/params_butterfly.go
  build/buildconstants/params_calibnet.go
  build/buildconstants/params_interop.go
  build/buildconstants/params_mainnet.go
  build/buildconstants/params_testground.go
  chain/lf3/config.go
Labels: skip/changelog

#12830 fix(drand): add null HistoricalBeaconClient for old beacons
  CHANGELOG.md
  README.md
  chain/beacon/drand/drand.go
  chain/beacon/drand/drand_test.go
  documentation/en/cli-lotus-miner.md
  documentation/en/cli-lotus-worker.md
  documentation/en/cli-lotus.md
  go.mod
  go.sum
Labels: skip/changelog

#12937 chore: reduce participation log verbosity when F3 isn't ready
  chain/lf3/participation.go
Labels: skip/changelog

#12935 fix: delegate integer operations to go-state-types
  chain/types/bigint.go
Labels: skip/changelog

#12943 fix: f3: topic filter with no static manifest
  node/modules/lp2p/pubsub.go
Labels: skip/changelog

#12949 fix: f3: use F3InitialPowerTableCID in contract provided manifests
  chain/lf3/manifest.go
Labels: skip/changelog

#12948 fix: prevent panic in `FullNodeProxy` with empty node list
  cli/util/api.go
Labels: skip/changelog

#12950 fix(index): avoid deadlock on close
  chain/index/indexer.go
Labels: skip/changelog

#12942 chore(fees): add initial fees & migration testing (FIP-0100)
  CHANGELOG.md
  api/api_full.go
  build/openrpc/full.json
  build/openrpc/gateway.json
  chain/actors/builtin/miner/actor.go.template
  chain/actors/builtin/miner/miner.go
  chain/actors/builtin/miner/state.go.template
  chain/actors/builtin/miner/v0.go
  chain/actors/builtin/miner/v10.go
  chain/actors/builtin/miner/v11.go
  chain/actors/builtin/miner/v12.go
  chain/actors/builtin/miner/v13.go
  chain/actors/builtin/miner/v14.go
  chain/actors/builtin/miner/v15.go
  chain/actors/builtin/miner/v16.go
  chain/actors/builtin/miner/v2.go
  chain/actors/builtin/miner/v3.go
  chain/actors/builtin/miner/v4.go
  chain/actors/builtin/miner/v5.go
  chain/actors/builtin/miner/v6.go
  chain/actors/builtin/miner/v7.go
  chain/actors/builtin/miner/v8.go
  chain/actors/builtin/miner/v9.go
  documentation/en/api-v0-methods.md
  documentation/en/api-v1-unstable-methods.md
  itests/daily_fees_test.go
  itests/direct_data_onboard_test.go
  itests/direct_data_onboard_verified_test.go
  itests/kit/funds.go
  itests/kit/node_unmanaged.go
  itests/manual_onboarding_test.go
  itests/niporep_manual_test.go
  node/impl/full/state.go
Labels: skip/changelog

#12956 chore: make function comment match function name
  itests/fevm_test.go
Labels: skip/changelog

#12951 chore: set nv25 calibnet upgrade epoch
  build/buildconstants/params_calibnet.go
Labels: skip/changelog

#12964 chore: update Calibration Teep height
  build/buildconstants/params_calibnet.go
Labels: skip/changelog

#12966 chore: update butterfly network assets
  build/buildconstants/params_butterfly.go
  build/genesis/butterflynet.car.zst
Labels: skip/changelog

#12968 feat: integrate & test FIP-0098 additions
  chain/actors/builtin/miner/actor.go.template
  chain/actors/builtin/miner/miner.go
  chain/actors/builtin/power/actor.go.template
  chain/actors/builtin/power/power.go
  chain/actors/policy/policy.go
  chain/actors/policy/policy.go.template
  go.mod
  go.sum
  itests/sector_terminate_test.go
Labels: release/backport, skip/changelog

#12974 chore(shed): update miner actor from v15 to v16 in `lotus-shed miner` cmd
  cmd/lotus-shed/miner.go
Labels: skip/changelog

#12980 feat(shed): lotus-shed miner-fees - to inspect FIP-0100 fees for a miner
  cmd/lotus-shed/main.go
  cmd/lotus-shed/miner-fees.go
Labels: release/backport, skip/changelog

#12978 feat: expose market ProviderSectors access on state-types abstraction
  CHANGELOG.md
  chain/actors/builtin/market/actor.go.template
  chain/actors/builtin/market/market.go
  chain/actors/builtin/market/state.go.template
  chain/actors/builtin/market/v0.go
  chain/actors/builtin/market/v10.go
  chain/actors/builtin/market/v11.go
  chain/actors/builtin/market/v12.go
  chain/actors/builtin/market/v13.go
  chain/actors/builtin/market/v14.go
  chain/actors/builtin/market/v15.go
  chain/actors/builtin/market/v16.go
  chain/actors/builtin/market/v2.go
  chain/actors/builtin/market/v3.go
  chain/actors/builtin/market/v4.go
  chain/actors/builtin/market/v5.go
  chain/actors/builtin/market/v6.go
  chain/actors/builtin/market/v7.go
  chain/actors/builtin/market/v8.go
  chain/actors/builtin/market/v9.go
  go.mod
  go.sum
  itests/direct_data_onboard_test.go
Labels: release/backport

#12982 fix: take in NetworkName in shed f3 check-activation
  cmd/lotus-shed/f3.go
Labels: skip/changelog

#12981 feat(shed): inspect miner fee payment at each deadline cron
  cmd/lotus-shed/main.go
  cmd/lotus-shed/miner-fees.go
  cmd/lotus-shed/miner.go
Labels: skip/changelog

#12993 refactor: use the built-in max/min to simplify the code
  chain/actors/policy/policy.go
  chain/actors/policy/policy.go.template
Labels: skip/changelog

#12985 chore: make fiximports run in parallel
  scripts/fiximports/main.go
Labels: skip/changelog

#12984 feat(shed): lotus-shed miner list-balances
  cmd/lotus-shed/miner.go
Labels: skip/changelog
